### ISSUE TITLE
mpv bug

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#105]
X-en sem, waylandon sem, egyik verzió sem indul. (35.1, 35.0, 34.1)  
Példa MATE alatt:
>attila@derp-x8664:~/Videók/MPEG-4 Video (Simple Profile)$ mpv small.avi
 (+) Video --vid=1 (mpeg4 560x320 30.000fps)
 (+) Audio --aid=1 (mp3 1ch 48000Hz)
[vo/gpu] VT_GETMODE failed: Inappropriate ioctl for device
[vo/gpu/opengl] Failed to set up VT switcher. Terminal switching will be unavailable.
[vo/gpu/opengl] Failed to set CRTC for connector 61: Permission denied
Error opening/initializing the selected video_out (--vo) device.
Video: no video
>
>Exiting... (Errors when loading file)
attila@derp-x8664:~/Videók/MPEG-4 Video (Simple Profile)$ 

UBK3-on X-en megy, GNOME/wayland mesa-19.2.7 nvidia-GTX 660 Ti nem. GNOME/wayland mesa-19.2.7 nvidia-GF 210 jó! Az MPLAYER mindenütt jó!

**Comment by attuska** [comment]
A mesa verzió nekem gyanús...

**Comment by attuska** [comment]
Inkább a libdrm...

**Comment by attuska** [comment]
Találtam egy lezárt issuet hasonló probémával!
https://github.com/mpv-player/mpv/issues/9773

**Comment by attuska** [comment]
Az x.org-video-nouveau csoamg sem segít.

**Comment by attuska** [comment]
UBK4 MATE, laptotty
Hardinfo Graphics:
>Intel Mobile 4 Series Chipset Integrated Grapics + Intel Mobile Series Chipset Integrated Graphics 1344x768
>The X.org Foundation 21.1.7

>attila@derp-x8664:~/Videók$ mpv sample_640x360.avi
 (+) Video --vid=1 (mpeg4 640x360 29.970fps)
[vo/gpu] VT_GETMODE failed: Inappropriate ioctl for device
[vo/gpu/opengl] Failed to set up VT switcher. Terminal switching will be unavailable.
[vo/gpu/opengl] Failed to set CRTC for connector 61: Permission denied
Error opening/initializing the selected video_out (--vo) device.
Video: no video
No video or audio streams selected.
>
>Exiting... (Errors when loading file

glxinfo részletek:

>Extended renderer info (GLX_MESA_query_renderer):
 >   Vendor: Intel (0x8086)
 >   Device: Mesa Mobile Intel® GM45 Express Chipset (CTG) (0x2a42)
 >   Version: 22.3.3
 >    Accelerated: yes
 >   Max GLES1 profile version: 1.1
 >   Max GLES[23] profile version: 2.0


A celluloid jó. Nem az nvidia GPU a bűnös!

**Comment by attuska** [comment]
A mesa csomagunkat kevertem gyanúba, mert  csakis ő a felelős az OpenGL előállítására, amelynek műkődnie kellene nálunk is, nem csak a rolling disztróknál! Ezeknél ilyen verzió nincs! Az időszakos kiadásúak közül az alap DEBIAN nem ad forrást, az alap Fedora utolsója a 32-es, de ez csak git forrásból elérhető és a régi cuccokat mind törlik. A csomagunk csak a réginek egyszerű verzószámemelésével és foltkiegészítésekkel készült. Egyedül a BLFS-nél van ez a verzió még:
https://www.linuxfromscratch.org/blfs/view/stable/x/mesa.html
Meg kellene kísérelni ez alapján elkészíteni a mesa-t, de a mienk szét van szabdalva még a régmúlt időkből.
(Nem kis feladat ez sem...)
UBK5-ön ki sem próbálom, az ottani cuccokkal mert biztos vagyok, hogy ott sem megy.

**Comment by attuska** [comment]
A BLFS féle mesa-val  is (csak a compile fázis más) ugyanaz a hibüzenet a terminálban.

**Comment by rezso** [comment]
> A mesa csomagunkat kevertem gyanúba, mert csakis ő a felelős az OpenGL előállítására, amelynek műkődnie kellene nálunk is, nem csak a rolling disztróknál! Ezeknél ilyen verzió nincs! Az időszakos kiadásúak közül az alap DEBIAN nem ad forrást, az alap Fedora utolsója a 32-es, de ez csak git forrásból elérhető és a régi cuccokat mind törlik. A csomagunk csak a réginek egyszerű verzószámemelésével és foltkiegészítésekkel készült. Egyedül a BLFS-nél van ez a verzió még: https://www.linuxfromscratch.org/blfs/view/stable/x/mesa.html Meg kellene kísérelni ez alapján elkészíteni a mesa-t, de a mienk szét van szabdalva még a régmúlt időkből. (Nem kis feladat ez sem...) UBK5-ön ki sem próbálom, az ottani cuccokkal mert biztos vagyok, hogy ott sem megy.

https://src.fedoraproject.org/rpms/mesa/c/c0a94403d7d6408b3ef35bda8e22b92e91704292?branch=rawhide
Azaz volt 22.3.3-as mesa verzió Fedora 37-ben és 38-ban.
Amúgy ki szedte szét a mesa csomagot? :)

**Comment by attuska** [comment]
>Amúgy ki szedte szét a mesa csomagot?

Én szedtem szét az OpenGL felelős mesa-t, már rohadt rég. Rá sem néztem azóta, de az UBK3 X-en még jó volt az mpv és jó.
Újabban meg nem jó sehol sem, ez a száraz tény most.

A BLFS -féle mesa-t én mesonnal forgattam, azzal sem jó.
Egyelőre én feladtam.

**Comment by attuska** [comment]
Lehet, hogy az x.orgt-server postinst? Ez is én alkottam valaha, ez csinálja ugyanis a liblx.so szimlinket.
UBK4-en a szerver verzió 21.7, UBK3-on  1.20.5.

**Comment by rezso** [comment]
Én most ubk5 alatt ezeket módosítottam:

https://github.com/uhulinux/ub-ubk5/commit/add6276ca350e562d826139a3e67bc6d27bd3ce3

https://github.com/uhulinux/ub-ubk5/commit/980ad9030a222640c3137ee760e6aeb853facc29

Persze lehet még mesa install, x.org-server postinst is.

**Comment by rezso** [comment]
Érdekes eredménye lett a mesa módosításának. A geeqie induláskor "Unable to initialize Clutter: Unable to initialize the Clutter backend: no available drivers found." hibát ad.
A geeqie esetében ezt egy --disable-clutter opcióval ki lehet kerülni, de máshol is van probléma vele:
https://bugs.launchpad.net/ubuntu/+source/clutter-gtk/+bug/1974254
Akkor sem oldódik meg a probléma, ha visszateszem a korábbi mesa split-et. Lehet, hogy mégis kell az a bizonyos szimlink?

**Comment by attuska** [comment]
>Akkor sem oldódik meg a probléma, ha visszateszem a korábbi mesa split-et. Lehet, hogy mégis kell az a bizonyos szimlink?
Ezt a szimlinket én találtam ki valaha, eddig működött mindenütt. Most már nem! Nincs OpenGL X alatt sem a nyílt mesa grafikus meghajtóval. Nem minden alkalmazásnál derül ez ki, azt biztosan tudom, hogy a gnome OpenGL függő és ezt megoldották X alatt és wayland alatt is és a mostani cuccainkkal megy UBK4 alatt a gnome, minden nálam fellelhető nvidia és intel GPU val. De egy alapvető konzolos médialejátszónál, mint az mpv mennie kellene. Az Mplayer-be nem mélyedtem jobban, mert jó.

**Comment by attuska** [comment]
Letesztelem az UBK5 telepítményemen az új alkotásaidat. Pendrive-n van az UBK5 teszt telepítményem egyelőre, melyet most fel kell frissítenem elébb.

**Comment by attuska** [comment]
Megcsináltam az UBK5 telepítményt, naprakész.
Ezen ez a hibaüzenet:
>attila@derp-x8664:/run/media/attila/SSD-UBK4/home/attila/Videók/H.264 (High Profile)$ mpv small.m4v
mpv: error while loading shared libraries: libdc1394.so.25: cannot open shared object file: No such file or directory
attila@derp-x8664:/run/media/attila/SSD-UBK4/home/attila/Videók/H.264 (High Profile)$

**Comment by rezso** [comment]
Egy patch release megváltoztatja a lib főverziót? Remek. 2.2.6 -> libdc1394.so.25, 2.2.7 -> libdc1394.so.26
Újraforgattam vele a tőle függő 5 csomagot. Nekem Mate alatt X-en teljesen jó.
Érdekes, hogy az mpv csak az ffmpeg-en keresztül függ a libdc1394-től, a vlc közvetlenül, a vlc mégis remekül működött eddig is.

**Comment by attuska** [comment]
Majd letesztelem, ha hozzájutok.

**Comment by attuska** [comment]
Jó lett X alatt. Van OpenGL a nyílt forrású mesa-val, legalábbis az mpv már nem nyavalyog.

**Comment by attuska** [comment]
UBK4-en még mindig vacak.

**Comment by rezso** [comment]
Próbáld meg most. Variáltam kicsit az x.org-server, mesa, libglvnd és mpv csomagokon. (Amúgy az x.org-serverben nem volt dri3 támogatás, ami azért problémás néhol...)
És közben csináltam egy gyors statisztikát ubk5-ön: ott 20 csomag használ mesa-t, és 114 liglvnd-t. Szóval úgy tűnik, a mesa fokozatosan háttérbe szorul.

**Comment by attuska** [comment]
JÓ Mindenütt!!!
Köszi.
