### ISSUE TITLE
mpv wayland

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#11]
Nem játszik le videót az mpv és annak grafikus felülete a celluloid wayland felületen.
https://linuxreviews.org/Mpv_drops_GNOME_support

**Comment by rezso** [comment]
Már csak warning:
https://github.com/mpv-player/mpv/commit/cdaa496314f90412963f2b3211e18df72910066d

**Comment by attuska** [comment]
A GNOME észleléskori warning szerintem nem jó, mert az mpv GNOME-X felületen megy, jóllehet a GNOME alapértelmezettje a wayland.
Nem szabad frissíteni az mpv-t, mert akkor GNOME -n végképp használhatatlan lesz.
Ha wayland észlelésre térnek rá, akkor más más lesz az ábra. Gondolom Plasma wayland alatt is hasonló az ábra. A sway -t meg sem említem.
