### ISSUE TITLE
catfish not working

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#110]

**Comment by attuska** [comment]
A catfish 1.4.5.6 produktoma terminálban:
>attila@derp-x8664:~$ catfish
>
>(catfish:30592): Gtk-WARNING **: 09:10:46.050: ../gtk/gtkwidget.c:8652: widget not within a GtkWindow
Traceback (most recent call last):
  File "/bin/catfish", line 42, in <module>
    catfish.main()
  File "/usr/lib/python3.10/site-packages/catfish/__init__.py", line 76, in main
    window = CatfishWindow.CatfishWindow()
  File "/usr/lib/python3.10/site-packages/catfish_lib/Window.py", line 165, in __new__
    builder = get_builder(__builder__['ui_file'])
  File "/usr/lib/python3.10/site-packages/catfish_lib/helpers.py", line 67, in get_builder
    builder.add_from_file(ui_filename)
  File "/usr/lib/python3.10/site-packages/catfish_lib/Builder.py", line 87, in add_from_file
    ele_widgets = tree.getiterator("object")
AttributeError: 'ElementTree' object has no attribute 'getiterator'
attila@derp-x8664:~$

**Comment by attuska** [comment]
https://github.com/uhulinux/ub-ubk4/commit/76640069ba29e3662421728f26bb480f54698f3f
Befrissítve már elindul, van ablak, meg minden, de nem lehet vele keresni, használhatatlan ez az xfce4-hez való pythonos alkalmazás. Még javítandó lenne, ha lehet.
Kell ez egyáltalán?

**Comment by attuska** [comment]
Terminálból indítva a befrissítettet így üzenget:
>attila@derp-x8664:~$ catfish
/usr/lib/python3.10/site-packages/gi/overrides/Gtk.py:1689: Warning: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
 > return _Gtk_main(*args, **kwargs)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/catfish/CatfishWindow.py", line 2226, in perform_query
    self.get_window().set_cursor(Gdk.Cursor.new_from_name(
TypeError: constructor returned NULL

**Comment by attuska** [comment]
UBK3-on működik az 1.4.10 -es is, UBK4-en nem megy az 1.4-es sorozat sem, a 4.18.0 meg használhatatlan mindegyiken.

**Comment by rezso** [comment]
A kereséshez talán a plocate kell.

**Comment by attuska** [comment]
UBK4-en csak locate van, és ez a Krusader fájlkezelőben működik.
A pythonos catfish viszont nem. Hajlok rá, hogy kidobjam.

**Comment by rezso** [comment]
Én már kidobtam a catfish-t ubk5-ön, és ubk4-nél is töröltem a szerverről, a gitből még nem.
A locate-t pedig lecseréltem a plocate-ra, egyszerűbbnek és gyorsabbnak tűnik.

**Comment by attuska** [comment]
A gittből kidobtam.
https://github.com/uhulinux/ub-ubk4/commit/677c8f7242b7f52897ba4047ba7a0ff882c68cf9
