### ISSUE TITLE
gnome-flashback no panels

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#111]
Újabban a gnome-flashback munkamenetben eltűntek a panelek.

**Comment by attuska** [comment]
Szerencsére az egér jobb szemére klikkelve előjön egy menü, amiből egy grafikus terminál nyitható.
Ebben kiasva a gnome-panel parancsot mér felbukkannak az alpértelmezett panelek és a rajta levő cuccok is működnek, a panelek is módosíthatók rendben.
A terminált elhagyva a panelek újból eltűnnek.
Valamiért a gnome-panel nem indul el automatikusan a munkamenetben. Nem tudom, hogy ezt miképpen lehetne beállítani és ez a beállítás hol tárolódik. Nincs ez az orromra kötve, bajlódjak vele? Én úgyis csak a MATE -t használom főként.

**Comment by attuska** [comment]
Új felhasználónál sincs panel, tehát nem a /home alatti cuccokban van a hiba.
Mellékesen az új felhasználó csak akkor tud belépni bárhová, ha üres a jelszava. Ez komolyabb hiba!

**Comment by rezso** [comment]
Nem nekem kellett sose a gnome-flashback, szóval én a magam részéről simán kidobom. Amúgy a session fájlban a required components listában benne van a panel is, tehát el kellene indulnia. Ha mégsem, akkor ott gond van.

**Comment by attuska** [comment]
Rájöttem. https://github.com/uhulinux/ub-ubk4/commit/108fb0abb9464b3f5d58beb06cd66e68ca1d1965
