### ISSUE TITLE
gcc bug

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#113]
A hibás commit: https://github.com/uhulinux/ub-ubk4/commit/f6b57227a5be810042b1c8a04293a37aae437207

**Comment by rezso** [comment]
Nem hibás a commit. Oka van. És ha azt hiszed, hogy a vdr fordítást meg tudod oldani a "hiányzó" szimlinkekkel, akkor nagyot tévedsz. Sőt, még a gcc újrafordítása sem fog menni azzal, hogy csinálsz egy revertet erre a commitra.

**Comment by attuska** [comment]
Sajnos mégis kellenek a szimlinkek. Bebizonyosodott.
Újrafordítottam a gcc-t (Nekem11 órába telt a lefordítása.), az installba beraktam a hiányzó szimlinket, amit töröltél, az egész VDR banda lefordult ma reggel export sorok nélkül az éjjel elkészült módosított gcc-vel.
(Még az icu forrásáben is van export CC=gcc
export CXX=g++ , ezek szerintem feleslegesek így már, de nem foglalkozom vele.)
Kommitolom a változtatásokat.
https://github.com/uhulinux/ub-ubk4/commit/c7763fead662ccb7623745da72383ac8f463b2f9

**Comment by rezso** [comment]
Szerintem felesleges volt a gcc újrafordítása a szimlinkekkkel, de te tudod...  Az icu esetében pedig azért van megadva, mert az először a clang++-t keresi, nem a g++-t.

**Comment by attuska** [comment]
A g++ -ra kerestem csak rá a compile fájlokban és ekkor bukott ki az icu is vdr cuccokkal egyetemben.
Azt, hogy ez miért lett megadva nem vizslattam, mert amúgyis rettegek az icu -tól.
