### ISSUE TITLE
Az új llvm -el nem fordulnak le egyes programok.

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#114]

**Comment by attuska** [comment]
Például a hedgewars:
>ISO C99 and later do not support implicit function declarations

**Comment by rezso** [comment]
Akkor ott include hiba lesz. Az "implicit function declaration" hiba akkor van, ha egy funkció nincs deklarálva egy fejlécben.

**Comment by attuska** [comment]
A hedgewars újrafordítását feladtam, nem éri meg a bajlódást. Lua nélkül is le lehetne fordítani, az ISO C99 hibák is leküzdhetők, de végén linkelési hiba van.
Legalább kiderült az sdl2 hibája, a javítottat felrakom.
