### ISSUE TITLE
lsmod, modprobe

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#118]

**Comment by attuska** [comment]
Próbáltam az nvidia csomagok küzül feltelpíteni, melyek a hardveres kártyámoz passzolnak, de már nem indul el a grafika, a rendszer nem ismeri fel az újabb kernel modult, ezért be sem tudja tölteni a modprobe.
Az lsmod sem sorol fel újabban feltelepítettet, csak a régieket.

**Comment by rezso** [comment]
Ez remélhetőleg megoldja: https://github.com/uhulinux/ub-ubk4/commit/ea1fae8886da6472c631da8020464facc9aef791
(Bár szerintem szimlinknek is működnie kellene...)

**Comment by attuska** [comment]
Sajnos nem működik.
Feltelepítettem a virtualbox csomagot, elfogadtam a telepítés közben a licencet a synaptic részletes baállító ablakjának termináljában az ottani angol billentyűzettel a z betűt nyomva, ami az y-t jelenítette meg, majd beállítódott. A feltelepített csomagok közt ez van:
>/usr/lib
/usr/lib/modules
/usr/lib/modules/6.1.68-1.x86_64
/usr/lib/modules/6.1.68-1.x86_64/misc
/usr/lib/modules/6.1.68-1.x86_64/misc/vboxdrv.ko
/usr/lib/modules/6.1.68-1.x86_64/misc/vboxnetadp.ko
/usr/lib/modules/6.1.68-1.x86_64/misc/vboxnetflt.ko

A modprobe vboxdrv kimenete rendszergazdai terminálban ez:
>root@derp-x8664:/home/attila# modprobe vboxdrv
modprobe: FATAL: Module vboxdrv not found in directory /lib/modules/6.1.68-1.x86_64
root@derp-x8664:/home/attila# 

Ez nem nvidia modul!

**Comment by attuska** [comment]
Nálam ez alapján: https://wiki.archlinux.org/title/NVIDIA ez a terminál kimenet működő grafikánál:

>attila@derp-x8664:~$ lspci -k | grep -A 2 -E "VGA|3D)"
>01:00.0 VGA compatible controller: NVIDIA Corporation GK104 [GeForce GTX 660 Ti] (rev a1)
>	Subsystem: ASUSTeK Computer Inc. Device 844b
>	Kernel driver in use: nouveau
>attila@derp-x8664:~$

**Comment by attuska** [comment]
Felfrissítettm a kernelt,virtualboxot, rendben elindult a rendszer.
Ámde továbbra is ez van:
>root@derp-x8664:/home/attila# modprobe vboxdrv
modprobe: FATAL: Module vboxdrv not found in directory /lib/modules/6.1.68-1.x86_64
root@derp-x8664:/home/attila# 

Most ezek a modulok a /lib/modules/6.1.68-1.x86_64/misc/ mappában vannak. Mekíséreltem átlinkelni őket a /lib/modules/6.1.68-1.x86_64/kernel/misc mappába, de továbbra sem leli meg a modprobe.
A modinfo nouveau kemenete normális.

**Comment by attuska** [comment]
Lehet, hogy a probléma csupán az, hogy a vinyóra utólag feltelepített modulok ismeretlenek. Újra kellene a ramdiszket ezért generáltatni ezért minden ilyen modul szállító csomagnál? Vagy megadni a grub kernel sorában paraméterként az illető modul(ok) nevé(ei)t ??

**Comment by attuska** [comment]
Íme az nvidia-390-es csomagunk forrásából a README.txt, mely szintén angol, amelyből szintén csak annyit értek nehezen, hogy le kellene tiltani a nouveau meghajtót, hogy használható legyen. Pár tanács is van benne ennek mikéntjéről, de csak megerősíti a gyanúmat, hogy az initramdiszk generálásába is bele kellne nyúlni ennek érvényesüléséhez.
[README.txt](https://github.com/uhulinux/ub-ubk4/files/14535519/README.txt)

**Comment by attuska** [comment]
A virtualbox csomag eltávolítás és újraindítáa után:
>root@derp-x8664:/home/attila# lsmod | grep vboxdrv

A csomagot felrakva:
root@derp-x8664:/home/attila# lsmod | grep vboxdrv
vboxdrv               512000  1 vboxnetflt
root@derp-x8664:/home/attila# modprobe vboxdrv
root@derp-x8664:/home/attila# 

Tehát a vinyón lévő /etc/modules.load.d alatt lévő vboxdrv.conf fájl a csomag feltelepítése után rögvest hatásos.
Az nvida modulokat viszont sehogyan sem találja, bárhova rakom is azokat.

**Comment by attuska** [comment]
Szerintem az egész "bűnös" committot https://github.com/uhulinux/ub-ubk4/commit/4f2af060890e8fc6cd7273de81c8ad1a1290fcf1 vissza kellene csinálni, mert ez eddig csak több kárt okozott, mint hasznot.
A valódi /lib mappával továbbra is működne minden itt UBK4-en. A szimlinkkel valami miatt nem akar, nem csak itt, hanem UBK5 alatt sem. UBK5-ön meg felőlem minden akadékoskodó, működésképtelen dolgot ki lehet hajtítani.

**Comment by attuska** [comment]
Kis "légypiszok" okozta az egész problémát a depmod hiánya a postinstben.
Kijavítottam őket. https://github.com/uhulinux/ub-ubk4/commit/03abd3e7546ae3d388b79136151c7e1739207866
Az általam tesztelhető csomagok, az nvidia-470, az nvidia-390, az nvidia 470 rendben működnek, de csak az X alatt.
