### ISSUE TITLE
wrong gcc version

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#119]

**Comment by attuska** [comment]
Próbálom újrafordítani az nvidia-490 csomagot, de nem megy.
A hibaüzenet:

>Compiler version check failed:
>
>The major and minor number of the compiler used to
>compile the kernel:
>
>gcc (GCC) 12.2.0, GNU ld (GNU Binutils) 2.40
>
>does not match the compiler used here:
>
>cc (GCC) 12.3.0

A kernelt talán újra kellene fordítani a gcc verzió megnövelése miatt ??

**Comment by rezso** [comment]
Nem talán, hanem biztosan. Plusz a többi, kernel modult tartalmazó csomagot is.
