### ISSUE TITLE
pipewire compilation error

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#124]
subprojects/wireplumber/meson.build:61:15: ERROR: Dependency 'libpipewire-0.3' is required but not found.

**Comment by rezso** [comment]
Frissíteni kell a pipewire-t. A wireplumber ugyanis gitből jön le, az aktuálisan utolsó committal, ami már újabb pipewire-t igényel.

**Comment by rezso** [comment]
Most aktuálisan pipewire 1.0.2 kell a wireplumbernek: https://github.com/PipeWire/wireplumber/blob/master/meson.build#L61

**Comment by rezso** [comment]
A mostani pipewire max. a wireplumber 0.4.81-ig támogatott. Szóval a subprojects/wireplumber.wrap fájlba kellene beírnod valahogy, hogy a wireplumber 0.4.81-et szedje le.
Vagy frissíted a pipewire-t legalább 1.0.2-re.
Vagy használod a -Dwireplumber=disabled opciót.

**Comment by attuska** [comment]
Akkor kénytelen leszek a pipewire ub-be belenyúlni, vagy patkolni, mert akkor, mikor a mostani pipewire verziónk készült, az akkor gittből leszedett wireplumber még támogatva volt, most módosítások nélkül nem fordítható le, azaz a kész UBK4 csomag nem reprodukálható. A pipewire frissítése meg itt UBK4-en nekem nem járható.

**Comment by attuska** [comment]
Megpatkoltam a wrap fájlt, hogy ne a head -et szedje le. A wireplumber 0.4.16 az utolsó, mellyel fordul a pipewire. Letiltására nincs lehetőség.

**Comment by attuska** [comment]
Kész.
https://github.com/uhulinux/ub-ubk4/commit/bb7ff6d615f0caf832bac61c17da600d524523ca
