### ISSUE TITLE
pysolfc tk bug?

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#126]
Nem indul.

Teljesen új telepítésen terminálban:
attila@derp-x8664:~$ pysol
Traceback (most recent call last):
  File "/bin/pysol", line 28, in <module>
    init()
  File "/usr/lib/python3.10/site-packages/pysollib/init.py", line 106, in init
    root = tkinter.Tk(className=pysollib.settings.TITLE)
  File "/usr/lib/python3.10/tkinter/__init__.py", line 2302, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: unknown color name "BACKGROUND"
attila@derp-x8664:~$ 

Google hasonló: https://github.com/corpnewt/ProperTree/issues/47

**Comment by rezso** [comment]
Ott van a megoldás is.

xrdb -load /dev/null
xrdb -query

Valószínűleg a mate-settings-daemon kavar be neki, az pakol mindenfélét az /etc/xrdb alá.
A gnome-settings daemon már 2010 végén kidobta ezt, most én is.
https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/commit/cc982caf2d02eeebf85ed763ddd4ca0819d72435
https://github.com/uhulinux/ub-ubk4/commit/0ae3be8973c042c9e8713a3abd0c434a2ef06f51

**Comment by attuska** [comment]
Jó lett.
