### ISSUE TITLE
nmap compile bug

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#127]

**Comment by attuska** [comment]
A régi eredeti ub-vel és az új frissítetndő ubk5 szerint módosítottnál is ez a lényeges hibaüzenet:
/bin/ld: cannot find libssh2/lib/libssh2.a: Nincs ilyen fájl vagy könyvtár.
Csak a --without-libssh2 compile opcióval fordítható le.

**Comment by rezso** [comment]
Mert régi a libssh2. Az nmap configure log megadja a választ.
