### ISSUE TITLE
compiz bug?

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#129]

**Comment by attuska** [comment]
A legutóbbi frissítések után nem használható.
>attila@derp-x8664:~$ compiz
Entity: line 1: parser error : Extra content at the end of the document
 name="force_independent_output_painting" type="bool"/></screen></core></compiz>
>                                                                               ^
>compiz (core) - Warn: Unable to parse XML metadata
attila@derp-x8664:~$ 

Tele van a google hasonló hibákkal  (Manjaro fórum például). Valószínűleg fel kell frissíteni uborka félére az ARCH(AUR) alapján... Az egész compiz sor így értelmetlen.

**Comment by rezso** [comment]
Semmi extra, csak a libxml2 is szigorúbb már, jobban megkövetel formai dolgokat is. Ugyanez van pl. a gettext 0.22-nél is, az sem tolerál már sok mindent. A compizosok meg adhatnának ki gyakrabban release-t.

**Comment by attuska** [comment]
Köszi Rezső! Megoldottad.
https://github.com/uhulinux/ub-ubk4/commit/fe9f80e688c378a5d60ac4fbab6889940f3d2716
