### ISSUE TITLE
Unable to compile js115

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#131]

**Comment by attuska** [comment]
Érdekes, hogy más disztróknál nincs ilyen gond. (Linuxmint, Arch, satöbbi.)

**Comment by rezso** [comment]
Mert azok nincsenek ennyire lemaradva. A rust simd nem fordul rust 1.78-tól, de ez a kissebb gond, mert a  --disable-rust-simd megoldaná. A nagyobb gond, hogy a c++ kód c++17-et igényelne, amit a 12-es gcc nem igazán támogat.... Vagy gcc 13 kellene, vagy az llvm libc++ libjét kellene használni, ami már az lvvm 17-től támogatja a c++17-et.

**Comment by rezso** [comment]
(Amúgy ubk5 alatt simán fordul, mert ott már gcc 13 van.)

**Comment by attuska** [comment]
Ha nem lesz, megoldva, akkor az egész cinnamont újra ki kell hajítani, vagy várni a linuxmintesekre.

**Comment by attuska** [comment]
Az újabb chromiumnak (rust,llvm) hála az egész cinnamon mehet újra a levesbe. De legalább a chromiumot elkészítetted sikeresen forrásból és használhatja, akinek az kell. Igaz, hogy a chromium forrása is folyamatosan frissül...
Akár az egész UBK4 is mehetne a levesbe...

**Comment by rezso** [comment]
Ennek semmi köze a chromiumhoz. A rust nem csak annak kell, és a --disable-rust-simd megoldja a rust problémát.
A libstdc++ viszont ettől még nem lesz újabb, és alapból az llvm is azt használja a c++ kódhoz.
A valós, tényleges probléma itt a gcc, azt kellene felfrissíteni, vagy az llvm libc++ használata.
De nyilván egyszerűbb vagdalkozni, mint átlátni a problémát. Amúgy hány u2d-be tettél "noupdate"-t, mert már nem frissíthető? Tetszik vagy sem, az ubk4 igencsak elérte a határait.

**Comment by rezso** [comment]
Ez nem megoldás, mert a js115 a gjs-nek is kell. Sőt, a polkit még a még régebbi js102-t használja - annál nem véletlenül cseréltem le a js-t duktape-ra az 5-ben.

**Comment by rezso** [comment]
A rust, ami 14 csomag elkészítéséhez kell, llvm függő, akár tetszik, akár nem. Szóval nem lehet a végletekig lefixálni sem a rust, sem az llvm verzióját. Most csináltam egy llvm18-at, amivel még a js102 is lefordul, de ennyi. Nem megy, hogy ahány csomag, annyiféle fordító... Ja és a gcc12-vel is lesznek még gondok előbb-utóbb.

**Comment by attuska** [comment]
A js115 az llvm-18-al sem fordul le, tehát a gjs sem reprodukálható többé. A polkit így a js102-vel (llvm18) rendben van, de a többi js115 függő cucc többé nem reprodukálható. Ez az ősiség átka. A rolling disztróknak meg, ahol minden a legfrissebb meg  más. Még a gentoo apróbb léptekkel halad, mint az Arch.

**Comment by attuska** [comment]
Lefordult a legújabb js115 az llvm18-al ezen az ósdi masinán. (1és fél óra...) Mehet vissza az újraforgatott cinnamon, a gjs-hez nem fogok hozzá, mert habár a mostaninak js102 kell, de a legújabbnak már js128 kellene, ami nincs.
Remélem, az llvm18 megmarad...
