### ISSUE TITLE
cinnamon polkit

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#135]
Be van dögölve a synaptic, meg bármi, ami root jogosultságú lenne.
https://bbs.archlinux.org/viewtopic.php?id=301680

**Comment by attuska** [comment]
Egy kép:
![synaptichiba](https://github.com/user-attachments/assets/49a78cca-58d0-4c26-9b2c-1684aef041ed)

**Comment by attuska** [comment]
Gentoo utolsó cinnamon ebuild-ja a 6.2.0, holott a cinnamon már a 6.4.3 -nál tart. A cinnamon-6.2.0-polkit-agent-on-x11.patch hatására már van jelszó bekérő ablak, de a sound appletnél ennél a verziónál hiba van. Ez a patch egy java cuccot foltoz ki, a 6.4,3-hoz nem passzol. A java nekem tök sötét, pythonból is elegem van.

**Comment by attuska** [comment]
A cinnamon-desktopot visszafejlesztve a Gentoo 6.2.0 verziójára a sound applet is jó a 6.2.0-val. A cinnamon 4.x-től felfele nélam bedöglik. Talán nem véletlen, hogy Gentoo sem lohol annyira a verziók után...

**Comment by attuska** [comment]
Visszafejlesztések rendbetették.
https://github.com/uhulinux/ub-ubk4/commit/a49077ca84ae9c6491cb9d675e4d6b39029bd7ce

**Comment by rezso** [comment]
Többek között az ilyen marhaságok miatt dobtam ki a cinnamon-t ubk5-ön. 6.4-hez 6.2-es desktop csomag kell, mert megdöglik? Na ne már...
