### ISSUE TITLE
synaptic méret karakter hiba

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#14]
A synaptic méret oszlopja olvashatatlan hieroglifákból áll.

**Comment by attuska** [comment]
![synaptic](https://user-images.githubusercontent.com/6311614/101935187-fab6e200-3bde-11eb-8396-b9787496d08b.jpg)

**Comment by rezso** [comment]
Tudjuk, csak azt nem, hogy mitől van.

**Comment by attuska** [comment]
MInden csomagnál azonos, szerintem a méret beazonosítás a hibás, mindegyik adat ugyanarról a helyről származik.

**Comment by attuska** [comment]
Debian megoldotta.
https://github.com/uhulinux/ub-ubk4/commit/1e141f289d9b88bb0e23125dfed4bd11517c869b
