### ISSUE TITLE
stuntrally segfault

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#15]
A tutorial részben:
>Loading resource group 'Car1Z' - Resources: 1 World Geometry: 1
Texture: ES_body00_brake.png: Loading 1 faces(PF_A8R8G8B8,1024x1024x1) with 5 hardware generated mipmaps from Image. Internal format is PF_A8R8G8B8,1024x1024x1.
Texture: ES_body00_add.png: Loading 1 faces(PF_A8R8G8B8,1024x1024x1) with 5 hardware generated mipmaps from Image. Internal format is PF_A8R8G8B8,1024x1024x1.
Finished loading resource group Car1Z
Terrain size: 513  err:5.00  batch: 65 129 /129
Terrain created; size=513 minBatch=65 maxBatch=129 treeDepth=3 lodLevels=4 leafLods=2
Szegmentálási hiba (core készült)
attila@attila-p5k:~$

**Comment by attuska** [comment]
A frissített ogre a hasraesés oka. Az ogre-1.9 -el simán megy. Fedora is ogre-1.9 -et használ, az a stabil, az ogre-1.9.1 már fejlesztői verzió. Egyszer már volt ilyen...
Vissza lesz fejlesztve az ogre.

**Comment by rezso** [comment]
Ha patch verzió emelés már dev verziónak számít, akkor az ultragány, kukába való cucc.

**Comment by attuska** [comment]
A stuntrally az ósdi, elhanyagolt cucc.

**Comment by rezso** [comment]
A dolog azért is érdekes, mert az ogre-t használja a cegui és mygui (na ezekből is minek kétféle?)
Az ap-ok közül csak a stuntrally és az opendungeons használja ténylegesen az ogre-t, az openmw és a tsc megvan nélküle, azaz sem a cegui-t, sem a mygui-t nem kell ogre-val forgatni ezeknek.
Csak itt meg az marad, hogy tsc + cegui, openmw + mygui.
Szóval az a kérdés, hogy kell-e az opendungeons. Ha nem, akkor stuntrally, opendungeons, ogre kuka, cegui és mygui pedig ogre nélkül is jó a tsc-nek és az openmw-nek.

Apropó, elhagyott cuccok: az alltray-nak van még valami szerepe? Működik? Van még értelme? Mert a libwnck2 csak ennek kell.

**Comment by attuska** [comment]
Már kész van mind, csak ki kell próbálni, ha jók, akkor még megkegyelmezek nekik

**Comment by attuska** [comment]
Megoldva. https://github.com/uhulinux/ub-ubk4/commit/36469365e41f345010fb85ab8057f1cd36d90014
