### ISSUE TITLE
enemy territory: unable to start

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#17]
Nem indítható a játék, hiánya van a ~/.etlegacy/legacy/crashlog.txt részlete:

>FS_CL_ExtractFromPakFile: failed to read 'ui.mp.x86_64.so' from pak file
Sys_LoadDll(legacy/ui) failed to extract library from fs_homepath
Sys_LoadDll(/home/attila/.etlegacy/legacy/ui.mp.x86_64.so)... failed: "Failed loading /home/attila/.etlegacy/legacy/ui.mp.x86_64.so: /home/attila/.etlegacy/legacy/ui.mp.x86_64.so: cannot open shared object file: No such file or directory"
>Sys_LoadDll(/usr/lib/etlegacy/legacy/ui.mp.x86_64.so)... failed: "Failed loading /usr/lib/etlegacy/legacy/ui.mp.x86_64.so: /usr/lib/etlegacy/legacy/ui.mp.x86_64.so: cannot open shared object file: No such file or directory"
Sys_LoadDll(legacy/ui) failed to load library

**Comment by rezso** [comment]
Valószínűleg a "121" nevű fájlban van, ami hol letölthető, hol nem.

**Comment by attuska** [comment]
Sajna még mindig nem indul, habár az előbb hiányolt fájl már létezik, de definiálatlan szimbólumon hasal el. (__acos_finite) Van bugreport belőle. https://github.com/etlegacy/etlegacy/issues/1527#issuecomment-731720676
>Sys_LoadGameDll -> FS_CL_ExtractFromPakFile(/home/attila/.etlegacy, legacy, ui.mp.x86_64.so)
Sys_LoadDll(/home/attila/.etlegacy/legacy/ui.mp.x86_64.so)... failed: "Failed loading /home/attila/.etlegacy/legacy/ui.mp.x86_64.so: /home/attila/.etlegacy/legacy/ui.mp.x86_64.so: undefined symbol: __acosf_finite"
Sys_LoadDll(/usr/lib/etlegacy/legacy/ui.mp.x86_64.so)... failed: "Failed loading /usr/lib/etlegacy/legacy/ui.mp.x86_64.so: /usr/lib/etlegacy/legacy/ui.mp.x86_64.so: cannot open shared object file: No such file or directory"
Sys_LoadDll(legacy/ui) failed to load library

**Comment by rezso** [comment]
Underlink probléma, a bináris, előre lefordított lib nincs rendesen összelinkelve a glibc-vel.
Ér ennyit ez a játék?

**Comment by attuska** [comment]
https://github.com/etlegacy/etlegacy/issues/1443#issuecomment-622534545
Úgy néz ki, hogy ezt az újabb glibc okozza és csak 64 biten.
Ha ez valóban így van, akkor kuka ez a játék UBK4 -en. Az enemy-territory-data -val egyetemben.

**Comment by attuska** [comment]
KIdobva a játék.
https://github.com/uhulinux/ub-ubk4/commit/8997d12042cd840e9d0496e5a37bdb1c8d95b1d8

**Comment by attuska** [comment]
Viszarakv a frissített már működik.
https://github.com/uhulinux/ub-ubk4/commit/5c44f72616f04238de6b5246b9e118ab45a44db6
