### ISSUE TITLE
mesa-extrademos/mesa-demos nem működik.

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#23]
Össze van gányolva az egész és nagyon hiányos. A menüből nem is indul.
>attila@attila-p5k:~$ mesa-demos
/bin/mesa-demos: 3. sor: cd: /usr/share/mesa-demos/objviewer: Nincs ilyen fájl vagy könyvtár
ls: '*.obj' nem érhető el: Nincs ilyen fájl vagy könyvtár
/bin/mesa-demos: 9. sor: cd: /usr/share/mesa-demos/demos: Nincs ilyen fájl vagy könyvtár

A /usr/bin alá szállított demó binárisok egy része működésképtelen adatfájlok híján.
Például:
>attila@attila-p5k:~$ teapot
Teapot V1.2
Written by David Bucciarelli (tech.hmw@plus.it)
../data/tile.rgb: No such file or directory
File not found
Error reading a texture.
attila@attila-p5k:~$ terrain
Error loading terrain.dat
attila@attila-p5k:~$ geartrain
Error: couldn't open ../data/geartrain.dat
attila@attila-p5k:~$

**Comment by rezso** [comment]
Előbb dobom ki a francba, mint hogy rendberakjam. Kell ez egyáltalán?
A szutyok widelands miatt is 9 (!) órán keresztül állt a gép. Ennyi idő alatt simán lefuthatott volna az egész sor.

**Comment by attuska** [comment]
Az infó cuccok azok kellenek. Például a glxgears, eglinfo. Ez utóbbi az extrademos-ban van most, a mesa-demos-ba illene.

**Comment by attuska** [comment]
Javítgattam rajta, most már valamennyire elfogadható.
https://github.com/uhulinux/ub-ubk4/commit/86aebb2224a8e5a111993b82e7ce145914ff27f3
