### ISSUE TITLE
sddm autologin bug

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#26]
Frissítés előtt és után is.
Ha a /etc/sddm.conf.d/Autologin.conf -ban ez van:

> [Autologin]
> Relogin=false
> Session=
> User=attila
akkor nem léptet be, és a systemctl status sddm ezt írja:

> sddm-helper-[2396]: [PAM] authenticate: A modul ismeretlen
>
> sddm-helper-[2396]: [PAM] returning.
>
> sddm [2388]: Authenticaton error: "A modul ismeretlen"
>
> sddm-helper-[2396]: [PAM] ended.
>
> sddm [2388]: Auth: sddm-helper exited with 1
>

Ha a konfigirációs fájlban az alapértelmezett van:

> [Autologin]
> Relogin=false
> Session=
> User=
akkor bejön az sddm üdvözlő kép és vígan be tudok lépni attila felhasználóként bárhova.

Végnéztem a pam sorokat az /etc/pam.d/sddm* fájlokban létezésre, van minden.

Egyelőre ezért a gdm-et használom, ott jó az autologin.

**Comment by rezso** [comment]
Rosszul nézted, mert a pam_tally illetve pam_tally2 nincs a pam 1.4.0-tól. Helyette a pam_faillock van.
Ugyanez a lightdm-nél is gond lehet, azt is javítom.

**Comment by attuska** [comment]
Törölnöm kellett a /etc/pam.d/sddm-autologin fájlból azokat a sorokat, melyekben pam_gnome_keyring.so van, hogy elsőre beléptessen, mert első nekifutásra nem talál jelszót a gkr. A systemctl restart sddm  ellenben már működik, az említett sorok eltávolításával viszont már első induláskor is jónak tűnik, beléptet, de a gnome-keyring jelszó bekérő ablakja továbbra is ott csúfoskodig első belépéskor, mint régen. Csak helyes jelszó begépelése után enged tovább, a jelszót úgy tűnik, hogy a gkr nem tárolja el, holott az lenne a feladata.

**Comment by attuska** [comment]
A gnome-keyring nem jegyzi meg a jelszót!
https://wiki.archlinux.org/index.php/GNOME/Keyring#Passwords_are_not_remembered
A seahorse csomagnak telepítve kellene lennie ehhez, viszont a seahorse csomagnak függősége vagy a gnome-keyring, vagy a keepassxc. https://archlinux.org/packages/extra/x86_64/seahorse/

**Comment by rezso** [comment]
A seahorse nem igényli a gnome-keyring-et. Kipróbáltam.
Amúgy pedig a belépési jelszó törölhető. https://askubuntu.com/questions/24770/gnome-keyring-keeps-asking-for-a-password-that-doesnt-exist

**Comment by attuska** [comment]
Amúgy a seahorse segítségével letörölt, üres jelszót sem tárolta el nekem a dög. Belépéskor újra erőszakoskodott a feldoldási jelszó bekérő ablakkal és az immáron üres jelszót sem fogadta el, hanem csakis a régit. Így inkább egyszerűen leszedtem a gnome-keyring csomagot, hogy el se tudjon indulni, habár a gnome-core meta csomag része még most. 
Nos, tehát az autologin probléma leszűkült a gnome-keyring problémára.
Lehet, hogy a gnome-keyring jelszó tárolójának, mely nem tudom, hogy hol van, csupán jogosultsági problémája van?
