### ISSUE TITLE
etlegacy

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#32]
Az etlagacy egyik nvidia hivatalos driverrel sem működik (nvidia-340, nvidia-390, nvidia). Kilép UBK3, UBK4 verzióban is. A mesa nouveau-val működik. Kísérteties a hasonlóság a speed-dreams problémával, az etl a mesával at etl ezt mondja:
>       0 ----- Initializing Renderer ----
>       0 SDL build version 2.0.14 - link version 2.0.14
>       0 SDL initialized driver "x11"
>       0 Initializing OpenGL display
>       0 Estimated display aspect: 1.333
>       0 ...setting mode -2: 1600x1200
>       0 Using 24 color bits, 24 depth, 0 stencil display
>       0 Available modes [8]: '640x480 800x600 832x624 1024x768 1152x864 1600x1200 1280x1024 720x400'
>       0 Using GLEW 2.1.0
>       0 GL_VENDOR: nouveau
>       0 GL_RENDERER: NVA8
>       0 GL_VERSION: 3.3 (Compatibility Profile) Mesa 19.2.7
>       0 GL_SHADING_LANGUAGE_VERSION: 3.30
>       0 Using vanilla renderer
>       0 Initializing OpenGL extensions
>       0 ...found OpenGL extension - GL_EXT_texture_compression_s3tc
>       0 ...found OpenGL extension - GL_EXT_texture_env_add
>       0 ...found OpenGL extension - GL_ARB_multitexture
>       0 GL_VENDOR: nouveau
>       0 GL_RENDERER: NVA8
>       0 GL_VERSION: 3.3 (Compatibility Profile) Mesa 19.2.7
>       0 GL_SHADING_LANGUAGE_VERSION: 3.30
>       0 GL_MAX_TEXTURE_SIZE: 8192
>       0 GL_MAX_ACTIVE_TEXTURES_ARB: 8
>       0 PIXELFORMAT: color(24-bits) Z(24-bit) stencil(0-bits)
>       0 MODE: -2, SCREEN: 1600 x 1200 windowed (ratio 1.3333) Hz:N/A
>       0 GAMMA: hardware w/ 0 overbright bits
>       0 texturemode: GL_LINEAR_MIPMAP_LINEAR
>       0 picmip: 0
>       0 texture bits: 32
>       0 multitexture: enabled
>       0 compiled vertex arrays: enabled
>       0 texenv add: enabled
>       0 compressed textures: enabled
>       0 Initializing Shaders
>       0 --------------------------------

A speed-dreams is NVA8 GL -t észlel.

**Comment by attuska** [comment]
nvidia-340:
>       0 ----- Initializing Renderer ----
>       0 SDL build version 2.0.14 - link version 2.0.14
>       0 SDL initialized driver "x11"
>       0 Initializing OpenGL display
>       0 Estimated display aspect: 1.333
>       0 ...setting mode -2: 1600x1200
>       0 Using 24 color bits, 24 depth, 0 stencil display
>       0 Available modes [5]: '640x480 800x600 1024x768 1600x1200 1280x1024'
>       0 Using GLEW 2.1.0
>       0 GL_VENDOR: NVIDIA Corporation
>       0 GL_RENDERER: GeForce 210/PCIe/SSE2
>       0 GL_VERSION: 3.3.0 NVIDIA 340.108
>       0 GL_SHADING_LANGUAGE_VERSION: 3.30 NVIDIA via Cg compiler
>       0 Using vanilla renderer
>       0 Initializing OpenGL extensions
>       0 ...found OpenGL extension - GL_EXT_texture_compression_s3tc
>       0 ...found OpenGL extension - GL_EXT_texture_env_add
>       0 ...found OpenGL extension - GL_ARB_multitexture
>       0 GL_VENDOR: NVIDIA Corporation
>       0 GL_RENDERER: GeForce 210/PCIe/SSE2
>       0 GL_VERSION: 3.3.0 NVIDIA 340.108
>       0 GL_SHADING_LANGUAGE_VERSION: 3.30 NVIDIA via Cg compiler
>       0 GL_MAX_TEXTURE_SIZE: 8192
>       0 GL_MAX_ACTIVE_TEXTURES_ARB: 4
>       0 PIXELFORMAT: color(24-bits) Z(24-bit) stencil(0-bits)
>       0 MODE: -2, SCREEN: 1600 x 1200 windowed (ratio 1.3333) Hz:N/A
>       0 GAMMA: hardware w/ 0 overbright bits
>       0 texturemode: GL_LINEAR_MIPMAP_LINEAR
>       0 picmip: 0
>       0 texture bits: 32
>       0 multitexture: enabled
>       0 compiled vertex arrays: enabled
>       0 texenv add: enabled
>       0 compressed textures: enabled
>       0 ----- Client Shutdown ----------
>       0 RE_Shutdown( 1 )
>       0 SDL input devices shut down.
>       0 --------------------------------

Feladja.

**Comment by attuska** [comment]
A legújabb nvidia meghajtóval UBK3 alatt is összetojja magát:
>       0 ----- Initializing Renderer ----
>       0 SDL build version 2.0.14 - link version 2.0.14
>       0 SDL initialized driver "x11"
>       0 Initializing OpenGL display
>       0 Estimated display aspect: 1.778
>       0 ...setting mode -2: 1920x1080
>       0 Using 24 color bits, 24 depth, 0 stencil display
>       0 Available modes [14]: '1280x720 1366x768 1600x900 1920x1080 1280x800 1440x900 1680x1050 720x480 640x480 800x600 1024x768 1152x864 720x576 1280x1024'
>       0 Using GLEW 2.1.0
>       0 GL_VENDOR: NVIDIA Corporation
>       0 GL_RENDERER: NVIDIA GeForce GTX 660 Ti/PCIe/SSE2
>       0 GL_VERSION: 4.6.0 NVIDIA 470.42.01
>       0 GL_SHADING_LANGUAGE_VERSION: 4.60 NVIDIA
>       0 Using vanilla renderer
>       0 Initializing OpenGL extensions
>       0 ...found OpenGL extension - GL_EXT_texture_compression_s3tc
>       0 ...found OpenGL extension - GL_EXT_texture_env_add
>       0 ...found OpenGL extension - GL_ARB_multitexture
>       0 GL_VENDOR: NVIDIA Corporation
>       0 GL_RENDERER: NVIDIA GeForce GTX 660 Ti/PCIe/SSE2
>       0 GL_VERSION: 4.6.0 NVIDIA 470.42.01
>       0 GL_SHADING_LANGUAGE_VERSION: 4.60 NVIDIA
>       0 GL_MAX_TEXTURE_SIZE: 16384
>       0 GL_MAX_ACTIVE_TEXTURES_ARB: 4
>       0 PIXELFORMAT: color(24-bits) Z(24-bit) stencil(0-bits)
>       0 MODE: -2, SCREEN: 1920 x 1080 windowed (ratio 1.7778) Hz:N/A
>       0 GAMMA: hardware w/ 0 overbright bits
>       0 texturemode: GL_LINEAR_MIPMAP_LINEAR
>       0 picmip: 0
>       0 texture bits: 32
>       0 multitexture: enabled
>       0 compiled vertex arrays: enabled
>       0 texenv add: enabled
>       0 compressed textures: enabled
>       0 ----- Client Shutdown ----------
>       0 RE_Shutdown( 1 )
>       0 SDL input devices shut down.
>       0 --------------------------------

**Comment by attuska** [comment]
Az előző etlegacy verziója elindul nvidia meghajtókkal is, csak épp használhatatlan, mert a beállítások után azonnal összetojja magát. Ez tehát egyértelműen etlagacy bug és nem nvidia driver.
Marad az új, és csakis nouveau meghajtóval nvidia GPU -k esetén.

**Comment by attuska** [comment]
A frissített nvidia és nvidia-390 meghajtókkal wayland felületen elindul, de tetű lassú.
Természetesen a GNOME/wayland csak a grub kernel sorába beillesztett nvidia-drm.modeset=1 opció esetén érhető el.
Érdekes.

**Comment by attuska** [comment]
A frissített etlagacy-2.78.0 sem megy nvidia meghajtóval, csak nouveau-val.

**Comment by attuska** [comment]
Új telepítésű UBK3-on nem indul újra.

**Comment by attuska** [comment]
UBK3 nvidia-240, GG-210, frisíiett SDL2 -vel (a régi sdl2-vel csak a verziószáma más):
>       0 --------------------------------
>       0 Creating PID file 'profiles/attila/profile.pid'
>       0 ----- Database Initialization --
>       0 SQLite3 libversion 3.32.3 - database URI 'etl.db' - in file
>       0 ... loading existing database '/home/attila/.etlegacy/etl.db'
>       0 ... database file '/home/attila/.etlegacy/etl.db' loaded
>       0 SQLite3 ETL: database init #2 /home/attila/.etlegacy/etl.db in [0] ms - autocommit 1
>       0 SQLite3 ETL: DB schema version #2 is up to date
>       0 --------------------------------
>       0 execing default.cfg
>       0 execing profiles/attila/etconfig.cfg
>       0 couldn't exec autoexec.cfg
>       0 Hunk_Clear: reset the hunk ok
>       0 Not logging server attacks to disk
>       0 ----- Client Initialization ----
>       0 Trying to load "librenderer_opengl1_x86_64.so" from "."...
>       0 Trying to load "librenderer_opengl1_x86_64.so" from "/usr/lib/etlegacy"...
>       0 ETKEY found
>       0 Available client translations: Afrikaans Bulgarian Catalan Czech Danish German Greek English Esperanto Spanish Finnish French Irish Hebrew Hungarian Italian Korean Dutch Norwegian Polish Portuguese Romanian Russian Slovak Slovenian Albanian Serbian Swedish Turkish
>       0 Available mod translations: Afrikaans Bulgarian Catalan Czech Danish German Greek English Esperanto Spanish Finnish French Irish Hebrew Hungarian Italian Korean Dutch Norwegian Polish Portuguese Romanian Russian Slovak Slovenian Albanian Serbian Swedish Turkish
>       0 Language set to Hungarian
>       0 --------------------------------
>       0 IP: 127.0.0.1
>       0 IP: 192.168.0.189
>       0 IP6: ::1
>       0 IP6: 2a01:36d:103:853d:d516:b506:9b16:8f73
>       0 IP6: fe80::9e0e:2cde:8757:7982%enp3s0
>       0 Opening IP6 socket: [::]:27960
>       0 Opening IP socket: 0.0.0.0:27960
>       0 Network initialized
>       0 ----- Initializing Renderer ----
>       0 SDL build version 2.24.0 - link version 2.24.0
>       0 SDL initialized driver "x11"
>       0 Initializing OpenGL display
>       0 Estimated display aspect: 1.250
>       0 ...setting mode 4: 800x600
>       0 Using 24 color bits, 24 depth, 0 stencil display
>       0 Available modes [5]: '1280x1024 640x480 800x600 1024x768 1280x960'
>       0 Using GLEW 2.1.0
>       0 GL_VENDOR: NVIDIA Corporation
>       0 GL_RENDERER: GeForce 210/PCIe/SSE2
>       0 GL_VERSION: 3.3.0 NVIDIA 340.108
>       0 GL_SHADING_LANGUAGE_VERSION: 3.30 NVIDIA via Cg compiler
>       0 Using vanilla renderer
>       0 Initializing OpenGL extensions
>       0 ...found OpenGL extension - GL_EXT_texture_compression_s3tc
>       0 ...found OpenGL extension - GL_EXT_texture_env_add
>       0 ...found OpenGL extension - GL_ARB_multitexture
>       0 GL_VENDOR: NVIDIA Corporation
>       0 GL_RENDERER: GeForce 210/PCIe/SSE2
>       0 GL_VERSION: 3.3.0 NVIDIA 340.108
>       0 GL_SHADING_LANGUAGE_VERSION: 3.30 NVIDIA via Cg compiler
>       0 GL_MAX_TEXTURE_SIZE: 8192
>       0 GL_MAX_ACTIVE_TEXTURES_ARB: 4
>       0 PIXELFORMAT: color(24-bits) Z(24-bit) stencil(0-bits)
>       0 MODE: 4, SCREEN: 800 x 600 windowed (ratio 1.3333) Hz:N/A
>       0 GAMMA: hardware w/ 0 overbright bits
>       0 texturemode: GL_LINEAR_MIPMAP_NEAREST
>       0 picmip: 2
>       0 texture bits: 0
>       0 multitexture: enabled
>       0 compiled vertex arrays: enabled
>       0 texenv add: enabled
>       0 compressed textures: enabled
>       0 Setting up FBO
>       0 ----- Client Shutdown ----------
>       0 RE_Shutdown( 1 )
>       0 SDL input devices shut down.
>       0 --------------------------------
>       0 PID file removed.
>       0 Network shutdown
>attila@attila-pc:~$ 

`

**Comment by attuska** [comment]
Találtam egy oldalt (google):https://etlegacy.readthedocs.io/en/latest/cvars.html#r-renderer
Az etl +set r_mode szám paranccsal meg lehet változtatni a kívánt grafikus felbontást, de ez nálam eddig eredménytelen.
Ha az Intel GPU-kkal sem megy, akkor ennek a játéknak a sorsa is mepecsételődött.

**Comment by attuska** [comment]
UBK3 alatt az sdl2 banda befrissítése okozza a gondot, a widelands is az újakkal seggreült, a régiekkel jó.
Csak az UBK4-en vacak.

**Comment by attuska** [comment]
UBK4 (FF ti) is vacak a nouveauval.

**Comment by attuska** [comment]
Nem nvida bug! Intel GPU-s laptottyon is teljes képpel kezd és bele is ragad. Csak konzolról lehet kilőni a killall etl paranccsal, de akkor is ugyanúgy Ctrl+C-t kell nyoni a terminálban. Ebben az alábbi üzenet van:
>attila@derp-x8664:~$ etl
>       0 ET Legacy 2.80-dirty linux-x86_64 May  8 2022
>       0 Zone megs: 64
>       0 INFO: fs_game now defaults to 'legacy' mod instead of 'etmain'
>       0 ----- Initializing Filesystem --
>       0 Current working directory:
>       0     /home/attila
>       0 Current search path:
>       0     D /home/attila/.etlegacy/legacy
>       0     D /usr/lib/etlegacy/legacy
>       0     D /home/attila/.etlegacy/etmain
>       0     D /usr/lib/etlegacy/etmain
>       0     P /usr/lib/etlegacy/legacy/legacy_v2.80.2.pk3 (1390 files)
>       0     P /usr/lib/etlegacy/etmain/pak2.pk3 (22 files)
       0     P /usr/lib/etlegacy/etmain/pak1.pk3 (10 files)
       0     P /usr/lib/etlegacy/etmain/pak0.pk3 (3725 files)
       0 
       0 5147 files in pk3 files
       0 --------------------------------
       0 ----- Database Initialization --
       0 SQLite3 libversion 3.39.0 - database URI 'etl.db' - in file
       0 ... loading existing database '/home/attila/.etlegacy/etl.db'
       0 ... database file '/home/attila/.etlegacy/etl.db' loaded
       0 SQLite3 ETL: database init #2 /home/attila/.etlegacy/etl.db in [0] ms - autocommit 1
       0 SQLite3 ETL: DB schema version #2 is up to date
       0 --------------------------------
       0 execing default.cfg
       0 couldn't exec etconfig.cfg
       0 couldn't exec autoexec.cfg
       0 Hunk_Clear: reset the hunk ok
       0 Not logging server attacks to disk
       0 ----- Client Initialization ----
       0 Trying to load "librenderer_opengl1_x86_64.so" from "."...
       0 Trying to load "librenderer_opengl1_x86_64.so" from "/usr/lib/etlegacy"...
       0 ETKEY found
       0 Available client translations: Afrikaans Bulgarian Catalan Czech Danish German Greek English Esperanto Spanish Finnish French Irish Hebrew Hungarian Italian Korean Dutch Norwegian Polish Portuguese Romanian Russian Slovak Slovenian Albanian Serbian Swedish Turkish
       0 Available mod translations: Afrikaans Bulgarian Catalan Czech Danish German Greek English Esperanto Spanish Finnish French Irish Hebrew Hungarian Italian Korean Dutch Norwegian Polish Portuguese Romanian Russian Slovak Slovenian Albanian Serbian Swedish Turkish
       0 Language set to English
       0 --------------------------------
       0 IP: 127.0.0.1
       0 IP: 192.168.0.177
       0 IP6: ::1
       0 IP6: fe80::fa15:e4a5:b59a:14f2%wlp2s0
       0 Opening IP6 socket: [::]:27960
       0 WARNING: NET_IP6Socket: bind: Address already in use
       0 Opening IP6 socket: [::]:27961
       0 Opening IP socket: 0.0.0.0:27960
       0 WARNING: NET_IPSocket - bind: Address already in use
       0 Opening IP socket: 0.0.0.0:27961
       0 Network initialized
       0 ----- Initializing Renderer ----
       0 SDL build version 2.0.20 - link version 2.0.22
       0 SDL initialized driver "x11"
       0 Initializing OpenGL display
       0 Estimated display aspect: 1.779
       0 ...setting mode -2: 1366x768
       0 Using 24 color bits, 24 depth, 0 stencil display
       0 Available modes [29]: '320x180 432x243 480x270 512x288 640x360 720x405 800x450 864x486 960x540 1024x576 1280x720 1366x768 360x202 684x384 640x400 840x525 960x600 700x450 320x240 400x300 512x384 640x480 700x525 800x600 896x672 928x696 960x720 1024x768 640x512'
       0 Using GLEW 2.2.0
       0 GL_VENDOR: Intel
       0 GL_RENDERER: Mesa Mobile Intel® GM45 Express Chipset (CTG)
       0 GL_VERSION: 2.1 Mesa 22.0.1
       0 GL_SHADING_LANGUAGE_VERSION: 1.20
       0 Using vanilla renderer
       0 Initializing OpenGL extensions
       0 ...found OpenGL extension - GL_EXT_texture_compression_s3tc
       0 ...found OpenGL extension - GL_EXT_texture_env_add
       0 ...found OpenGL extension - GL_ARB_multitexture
       0 GL_VENDOR: Intel
       0 GL_RENDERER: Mesa Mobile Intel® GM45 Express Chipset (CTG)
       0 GL_VERSION: 2.1 Mesa 22.0.1
       0 GL_SHADING_LANGUAGE_VERSION: 1.20
       0 GL_MAX_TEXTURE_SIZE: 8192
       0 GL_MAX_ACTIVE_TEXTURES_ARB: 8
       0 PIXELFORMAT: color(24-bits) Z(24-bit) stencil(0-bits)
       0 MODE: -2, SCREEN: 1366 x 768 fullscreen (ratio 1.7786) Hz:N/A
       0 GAMMA: hardware w/ 0 overbright bits
       0 texturemode: GL_LINEAR_MIPMAP_NEAREST
       0 picmip: 1
       0 texture bits: 0
       0 multitexture: enabled
       0 compiled vertex arrays: enabled
       0 texenv add: enabled
       0 compressed textures: enabled
       0 Setting up FBO
       0 ----- Client Shutdown ----------
       0 RE_Shutdown( 1 )
tty]DOUBLE SIGNAL FAULT: Received signal 15, exiting...
^CDOUBLE SIGNAL FAULT: Received signal 2, exiting...
       0 Sys_Exit warning - PID file doesn't exist /home/attila/.etlegacy/legacy/profiles//profile.pid
       0 Network shutdown
attila@derp-x8664:~$

**Comment by attuska** [comment]
A frissített UBK4-en is hibás a nouveauval. Itt a mesa gl verziója 22.2.0

**Comment by attuska** [comment]
Az nvidia-470 csomaggal csak villan egyet a legacy felirat. A terminálban ezt hagyja:
attila@derp-x8664:~$ etl
       0 ^2ET Legacy 2.80-dirty linux-x86_64 Oct  9 2022
       0 Zone megs: 64
       0 INFO: fs_game now defaults to 'legacy' mod instead of 'etmain'
       0 ----- Initializing Filesystem --
       0 Current working directory:
       0     /home/attila
       0 Current search path:
       0     D /home/attila/.etlegacy/legacy
       0     D /usr/lib/etlegacy/legacy
       0     D /home/attila/.etlegacy/etmain
       0     D /usr/lib/etlegacy/etmain
       0     P /usr/lib/etlegacy/legacy/legacy_v2.80.2.pk3 (1390 files)
       0     P /usr/lib/etlegacy/etmain/pak2.pk3 (22 files)
       0     P /usr/lib/etlegacy/etmain/pak1.pk3 (10 files)
       0     P /usr/lib/etlegacy/etmain/pak0.pk3 (3725 files)
       0 
       0 5147 files in pk3 files
       0 --------------------------------
       0 ----- Database Initialization --
       0 SQLite3 libversion 3.39.3 - database URI 'etl.db' - in file
       0 ... loading existing database '/home/attila/.etlegacy/etl.db'
       0 ... database file '/home/attila/.etlegacy/etl.db' loaded
       0 SQLite3 ETL: database init #2 /home/attila/.etlegacy/etl.db in [1] ms - autocommit 1
       0 SQLite3 ETL: DB schema version #2 is up to date
       0 --------------------------------
       0 execing default.cfg
       0 couldn't exec etconfig.cfg
       0 couldn't exec autoexec.cfg
       0 Hunk_Clear: reset the hunk ok
       0 Not logging server attacks to disk
       0 ----- Client Initialization ----
       0 Trying to load "librenderer_opengl1_x86_64.so" from "."...
       0 Trying to load "librenderer_opengl1_x86_64.so" from "/usr/lib/etlegacy"...
       0 ETKEY found
       0 Available client translations: Afrikaans Bulgarian Catalan Czech Danish German Greek English Esperanto Spanish Finnish French Irish Hebrew Hungarian Italian Korean Dutch Norwegian Polish Portuguese Romanian Russian Slovak Slovenian Albanian Serbian Swedish Turkish
       0 Available mod translations: Afrikaans Bulgarian Catalan Czech Danish German Greek English Esperanto Spanish Finnish French Irish Hebrew Hungarian Italian Korean Dutch Norwegian Polish Portuguese Romanian Russian Slovak Slovenian Albanian Serbian Swedish Turkish
       0 Language set to English
       0 --------------------------------
       0 IP: 127.0.0.1
       0 IP: 192.168.0.182
       0 IP6: ::1
       0 IP6: fe80::b8c2:3fd2:4315:ee59%enp2s0
       0 Opening IP6 socket: [::]:27960
       0 Opening IP socket: 0.0.0.0:27960
       0 Network initialized
       0 ----- Initializing Renderer ----
       0 SDL build version 2.24.0 - link version 2.24.1
       0 SDL initialized driver "x11"
       0 Initializing OpenGL display
       0 Estimated display aspect: 1.778
       0 ...setting mode -2: 1920x1080
       0 Using 24 color bits, 24 depth, 0 stencil display
       0 Available modes [14]: '1280x720 1366x768 1600x900 1920x1080 1280x800 1440x900 1680x1050 720x480 640x480 800x600 1024x768 1152x864 720x576 1280x1024'
       0 Using GLEW 2.2.0
       0 GL_VENDOR: NVIDIA Corporation
       0 GL_RENDERER: NVIDIA GeForce GTX 660 Ti/PCIe/SSE2
       0 GL_VERSION: 4.6.0 NVIDIA 470.141.03
       0 GL_SHADING_LANGUAGE_VERSION: 4.60 NVIDIA
       0 Using vanilla renderer
       0 Initializing OpenGL extensions
       0 ...found OpenGL extension - GL_EXT_texture_compression_s3tc
       0 ...found OpenGL extension - GL_EXT_texture_env_add
       0 ...found OpenGL extension - GL_ARB_multitexture
       0 GL_VENDOR: NVIDIA Corporation
       0 GL_RENDERER: NVIDIA GeForce GTX 660 Ti/PCIe/SSE2
       0 GL_VERSION: 4.6.0 NVIDIA 470.141.03
       0 GL_SHADING_LANGUAGE_VERSION: 4.60 NVIDIA
       0 GL_MAX_TEXTURE_SIZE: 16384
       0 GL_MAX_ACTIVE_TEXTURES_ARB: 4
       0 PIXELFORMAT: color(24-bits) Z(24-bit) stencil(0-bits)
       0 MODE: -2, SCREEN: 1920 x 1080 fullscreen (ratio 1.7778) Hz:N/A
       0 GAMMA: hardware w/ 0 overbright bits
       0 texturemode: GL_LINEAR_MIPMAP_NEAREST
       0 picmip: 1
       0 texture bits: 0
       0 multitexture: enabled
       0 compiled vertex arrays: enabled
       0 texenv add: enabled
       0 compressed textures: enabled
       0 Setting up FBO
       0 ----- Client Shutdown ----------
       0 RE_Shutdown( 1 )
       0 SDL input devices shut down.
       0 --------------------------------
       0 Sys_Exit warning - PID file doesn't exist /home/attila/.etlegacy/legacy/profiles//profile.pid
       0 Network shutdown
attila@derp-x8664:~$ 
Ha az Inteles GPU-val sem megy, akkor egszerűbb kidobni, mint a hibáját kijavítani. UBK3-on működik.

**Comment by rezso** [comment]
Fedora / Arch nem szállítja az etlegacy-t. Nyilván nem véletlenül.
Egyébként a mesa 21-től már elkezdődött régi, legacy kódok kidobása, nyilván ez is befolyásolja a dolgokat.

**Comment by attuska** [comment]
Ellenben van belőle flatpak!

**Comment by attuska** [comment]
A flatpak csomag, melyet a gnome-software telepített, még gnome-waylandon is megy!
Az enemy-territory által előállított csomag jó, csak a mienk nem.
Akinek ez a lövöldözős csapatjáték kell, az használja azt!

**Comment by attuska** [comment]
UBK3-on az etlegacy-2.81 csomag már jónak tűnik!
