### ISSUE TITLE
xorg wmvare driver was compiled without KMS- and 3D support

### ISSUE THREAD

**Issue by sipizolix** [uhulinux/ub-ubk4#34]
Sziasztok!

Szerettem volna megnézni virtualboxban az UBK4-et. Sajnos a guest additions nem működik a fenti hiba miatt, így nem tudom teljes képernyőn sem megnézni.

Lehetne, hogy a fenti opciók bekerüljenek a vmware driverbe?

Köszi, és hajrá!

**Comment by rezso** [comment]
Frissítettem az x.org-video-vmware csomagot, próbáld meg azzal.

**Comment by sipizolix** [comment]
Tökéletes, hatalmas köszönet!
