### ISSUE TITLE
gnome-tweak-40 nem működik

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#35]
>attila@attila-systemproductname:~$ gnome-tweaks
>Traceback (most recent call last):
 > File "/usr/lib/python3.8/site-packages/gtweak/app.py", line 51, in do_activate
  >  self.win = Window(self, model)
  > File "/usr/lib/python3.8/site-packages/gtweak/tweakview.py", line 58, in __init__
    self._model.load_tweaks(self)
  >File "/usr/lib/python3.8/site-packages/gtweak/tweakmodel.py", line 107, in load_tweaks
  > mods = __import__("gtweak.tweaks", globals(), locals(), tweak_files, 0)
  >File "/usr/lib/python3.8/site-packages/gtweak/tweaks/tweak_group_font.py", line 113, in <module>
  >  FontXSettingsTweak(),
  >File "/usr/lib/python3.8/site-packages/gtweak/tweaks/tweak_group_font.py", line 41, in __init__
   > self.btn_full.set_active(self.settings["font-hinting"] == "full")
  >File "/usr/lib/python3.8/site-packages/gi/overrides/Gio.py", line 260, in __getitem__
   > raise KeyError('unknown key: %r' % (key,))
>KeyError: "unknown key: 'font-hinting'"
>^C
>attila@attila-systemproductname:~$ 

A régi jó.

**Comment by attuska** [comment]
https://gitlab.gnome.org/GNOME/gnome-tweaks/-/issues/331

**Comment by attuska** [comment]
Átmenetileg visszafejlesztve. https://github.com/uhulinux/ub-ubk4/commit/2730447bf1454d5d3c6473836db3e80576c49475

**Comment by attuska** [comment]
A python3-pygobject frissítése sem oldotta meg.

**Comment by rezso** [comment]
A gsettings-desktop-schemas is frissítendő 40.0-ra. Vagy kell két patch.
gnome-tweaks:
https://gitlab.gnome.org/GNOME/gnome-tweaks/-/merge_requests/59/diffs?commit_id=50f6581c475eacd9bba6c5ed33aa38e48dea6991

gsettings-desktop-schemas:
https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas/-/commit/eb3ffa88e42c7fcfe71d593339dac7e73c75bba2

**Comment by rezso** [comment]
Ezért sem lett volna szabad lefixálni a gnome-ot 3.38-nál.

**Comment by attuska** [comment]
A rebuild után már jó.
