### ISSUE TITLE
guvcview nem indul

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#41]
A régebbi (2.0.6-3) és a frissített (2.0.7-1) is:
>attila@attila-systemproductname:~$ guvcview
V4L2_CORE: Unable to find parent usb device.V4L2_CORE: Unable to find parent usb device.V4L2_CORE: Unable to find parent usb device.GUVCVIEW: version 2.0.7
GUVCVIEW: couldn't open /home/attila/.config/guvcview2/video0 for read: Nincs ilyen fájl vagy könyvtár
V4L2_CORE: (UVCIOC_CTRL_MAP) Error: Helytelen ioctl hívás az eszköznek
V4L2_CORE: (UVCIOC_CTRL_MAP) Error: Helytelen ioctl hívás az eszköznek
V4L2_CORE: (UVCIOC_CTRL_MAP) Error: Helytelen ioctl hívás az eszköznek
V4L2_CORE: (UVCIOC_CTRL_MAP) Error: Helytelen ioctl hívás az eszköznek
V4L2_CORE: (UVCIOC_CTRL_MAP) Error: Helytelen ioctl hívás az eszköznek
V4L2_CORE: (UVCIOC_CTRL_MAP) Error: Helytelen ioctl hívás az eszköznek
V4L2_CORE: (UVCIOC_CTRL_MAP) Error: Helytelen ioctl hívás az eszköznek
V4L2_CORE: (UVCIOC_CTRL_MAP) Error: Helytelen ioctl hívás az eszköznek
V4L2_CORE: (UVCIOC_CTRL_MAP) Error: Helytelen ioctl hívás az eszköznek
V4L2_CORE: (VIDIOC_ENUM_FRAMESIZES) - Error enumerating frame sizes
v4L2_CORE: Unable to enumerate frame sizes :Helytelen ioctl hívás az eszköznek
V4L2_CORE: (VIDIOC_ENUM_FRAMESIZES) - Error enumerating frame sizes
v4L2_CORE: Unable to enumerate frame sizes :Helytelen ioctl hívás az eszköznek
V4L2_CORE: (VIDIOC_ENUM_FRAMESIZES) - Error enumerating frame sizes
v4L2_CORE: Unable to enumerate frame sizes :Helytelen ioctl hívás az eszköznek
V4L2_CORE: (VIDIOC_ENUM_FRAMESIZES) - Error enumerating frame sizes
v4L2_CORE: Unable to enumerate frame sizes :Helytelen ioctl hívás az eszköznek
V4L2_CORE: (VIDIOC_ENUM_FRAMESIZES) - Error enumerating frame sizes
v4L2_CORE: Unable to enumerate frame sizes :Helytelen ioctl hívás az eszköznek
V4L2_CORE: (VIDIOC_ENUM_FRAMESIZES) - Error enumerating frame sizes
v4L2_CORE: Unable to enumerate frame sizes :Helytelen ioctl hívás az eszköznek
V4L2_CORE: (VIDIOC_ENUM_FRAMESIZES) - Error enumerating frame sizes
v4L2_CORE: Unable to enumerate frame sizes :Helytelen ioctl hívás az eszköznek
V4L2_CORE: (VIDIOC_ENUM_FRAMESIZES) - Error enumerating frame sizes
v4L2_CORE: Unable to enumerate frame sizes :Helytelen ioctl hívás az eszköznek
V4L2_CORE: (VIDIOC_ENUM_FRAMESIZES) - Error enumerating frame sizes
v4L2_CORE: Unable to enumerate frame sizes :Helytelen ioctl hívás az eszköznek
V4L2_CORE: (VIDIOC_ENUM_FRAMESIZES) - Error enumerating frame sizes
v4L2_CORE: Unable to enumerate frame sizes :Helytelen ioctl hívás az eszköznek
Cannot connect to server socket err = Nincs ilyen fájl vagy könyvtár
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Szegmentálási hiba (core készült)
attila@attila-systemproductname:~$

**Comment by attuska** [comment]
A full rebuild után is maradt az üzenet.

**Comment by rezso** [comment]
Azóta már újabb verzió is van. Ha nem gond.
