### ISSUE TITLE
AQEMU szegmentalasi hiba

### ISSUE THREAD

**Issue by miklosakos** [uhulinux/ub-ubk4#62]
Az AQEMU az alabbi hibaval szall el UBK4-en:
```
AQEMU Warning [2] >>>
Sender: bool Emulator::Load( const QString &path )
Message: No "qemu-system-ppcemb" element!

AQEMU Warning [4] >>>
Sender: bool Emulator::Load( const QString &path )
Message: No "qemu-system-ppcemb" element!
Szegmentálási hiba (core készült)
```
Ezekben az issuek-ban emlitve van: #tobimensch/aqemu#89, #tobimensch/aqemu#80, #tobimensch/aqemu#92.
A 92-es issue alapjan ez a hiba QEMU 3.10.0 es ujabb verziok ota van jelen, az UBK4 jelenleg a 6.2.0-ast szallitja.
A "dirty fix" a 89-esben van targyalva: src/System_Info.cpp-ben kell kikommentelni a ppcemb-t kereso kodot.
UBK4-ben a 0.9.2-es verziot szallitjuk, a kod 2 eve nem volt frissitve, a legfrisebb fejlesztoi verzio a 0.9.6.

**Comment by rezso** [comment]
https://github.com/uhulinux/ub-ubk4/commit/1436260a722806f99702a33e5b566935dec36bfb

**Comment by rezso** [comment]
Kidobva. https://github.com/uhulinux/ub-ubk4/commit/7b0b3dd621730f6bf05659178ec00f79244a001e
