### ISSUE TITLE
vdr képalkotási gondok

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#63]
Az eddig jól használható vdr-xineliboutput már szótlan és nem ad képalkotó ablakot. Az ffmpeg3.4 -el forgatva sem.
A vdr-softhddevice csak szoftveresen használható (workaround le lehet tiltani a beállításában), úgy képet ad és nem fagy le, mivel a nouveaunak nincs hardveres gyorsítása. A hivatalos nvidia-340 meghajtóval működne, annak lenne hardveres gyorsítása, de az még X -et sem ad. A régi x.org-szerverrel együttműködött az nvidia drájver és a sofhddevice és villámgyors volt még HD adásoknál is.
A kodi jól használható a vdr-hez, de annál is le kell tiltani a vdpau használatot és a libva -t is. A vdr-xine elég jó, csak a csatorna váltása igencsak nehézkes.

**Comment by rezso** [comment]
A vdr-xineliboutput utolsó release bő 2 éves. A github repó archivált, 3 éve nincs benne commit.
Az sf.net-en a git repó még aktív. https://sourceforge.net/p/xineliboutput/git/ci/master/tree/
Meg lehet próbálni azzal, ha meg nem megy, lehet reklamálni a fejlesztőnek. Nyilván sem a vdr, sem az ffmpeg nem fog megállni a xinelboutput miatt.

**Comment by attuska** [comment]
A vdr-xineliboutput így végzi:

`Magick:abort due to signal 11 (SIGSEGV) "Segmentation Fault"...
Félbeszakítva (core készült) 
attila@attila-systemproductname:~$`

**Comment by attuska** [comment]
A sourceforge gittből letöltött xineliboutput forrásból letöltött snapshotból és az ffmpeg -vel leforgatott csomag is seggreül.
Nálam használhatatlan. Marad a sofhddevice hardveres gyorsítás nélkül.

**Comment by attuska** [comment]
A kodival a DVBT szabadon foghatók csak akkor adnak képet is, ha a kodiban a libva gyorsítás le van tiltva. Műholdról a DVB S2 csatornáknál ad képet libva hardveres gyorsítással is. Minkét típus DVB stream pedig h264-es tömörítésű. A nouveau a vdpau-firmware segítségével tud hardweres  gyorsítást a vdpauinfo szerint.

**Comment by attuska** [comment]
A xineliboutput friss telepítésen jól működik.

**Comment by attuska** [comment]
Az egész vdr vuccot is ke lehet dobni, senki nem használja, vagy aki majd mégis, az majd keres magának más disztrót.
