### ISSUE TITLE
gnome-control-center & nvidia/wayland 

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#67]
A gnome elindul ugyan az nvida-390 és nvidia-470 csomagokkal is wayland felületen, de a gnome-control-center már nem. A beállításokat (háttérkép, satöbbi)  X -en lehet csak elvégezni, azok maradandók waylandon is!
A 390 -es egyszerűen feladja az egészet és kilép a gnome munkamenetből, a 470-el ugyan bennmarad, de semmit nem csinál. A nouveau meghajtóval teljesen jó, UBK3-an meg mindenképp jó.
Sötét egy ügy számomra, de az, hogy hiba ez az új gnómon, az biztos.
Az inernet tele van bugreporttal.

**Comment by rezso** [comment]
A gnome3 kezdetektől katasztrófa volt. Mindössze ezt a "nemes hagyományt" folytatják.

**Comment by attuska** [comment]
A régi frissített, jól belakott UBK4 telepítményemen most csak a gnome-flashback indul el, a mate, plasma, az lxqt, az xfce, az lxde, megt a primitív ablakkezelők. Betojt a cinnamon, a gome3 mindennel (wayland, nouveau, nvidia csomag), ő csak induláskor zenél, x-en szomorú pofa jön, waylandon meg visszadob zeneszó után az sddm beléptetőbe. **A friss telepítményemen ellenben jó, tehát a hiba az én készülékemben van.** Megpróbálom kideríteni, hogy mi a franc okozza, mielőtt újratelepítem. Valóban katasztrófa ez a gnome3, habár nekem mindig is tetszett. Vakarom le a sok felesleges cuccot, ez eltart jó darabig.

**Comment by attuska** [comment]
Új felhasználóval nincsen a telepítményen gond, tehát a /home/attila mappában van. Na, ezt nem lesz könnyű kinyomozni...

**Comment by attuska** [comment]
Az új, felfrissített telepítményen a hiba nem jelentkezik.
