### ISSUE TITLE
gnome-keyring és az automata beléptetés

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#68]
A gnome-keyring csomag feltetelepítése után eltárolja ugyan a kulcsra az user jelszavát, de a gdm, sddm, lightdm automatikus belétetés használatával mindig kéri a feloldási jelszót, mert szerinte nincs feloldva. Hibás jelszó megadásával újra kér a feloldási jelszót, a munkamenetbe nem lehet belépni, csak a reset gomb, vagy a helyes jelszó a megoldás.
PAM hiba lesz ez!

**Comment by attuska** [comment]
Ha a /etc/pam.d/system.auth fájlban a gnome-keyring sorok előtti # jeleket kivesszük, akkor a nem automata beléptetéskor a jelszóbekérő ablak nem jelentkezik többé. Automatikusnál továbbra is van! Teszteltem a gdm, sddm, lightdm grafikus beléptetőkkel.

**Comment by attuska** [comment]
Ez megoldhatatlannak tűnik automatikus beléptetéssel.
Inkébb kiszedem a gnome-core metacsomagból ezen amúgyis opcionálisan használandó csomag kötelező feltelepíttetését.
Ha valaki lemond az automatikus beléptetés lehetőségéről, akkor teljesen jó. A bejelenkezési jelszó egyszeri begépelése a beléptető feleleten már elegendő. A seahorse -val kiüresített jelszó is hatástalan, legalábbis nálam.

**Comment by rezso** [comment]
Nem csak a beléptetést állítja fejre, hanem a chromium, opera és más programok használatát is. Az egyetlen megoldás, hogy pl. a seahorse használatával töröljük a keyring jelszót.

**Comment by attuska** [comment]
Ezért én nem használom, egyszerűen leszedtem az egész gnome-keyring csomagot. Ez az egész nem az users csoport tagjainak készült. A meta csomagba meg nem szabad betenni, akinek mégis mazohista módon kell, az felteheti magának külön. Jó ez, csak nem nekünk.
