### ISSUE TITLE
illegális utasítások

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#71]
tulip:
Érvénytelen utasítás (core készült)

**Comment by attuska** [comment]
A hiba az ÖN készülékében van!
A -03 hatására a lapoppban lévő intel processzoron olyan utasítást generál, melyet az én amd processzorom az asztali gépemben nem tud értelmezni. Ismerős a hiba.
Az én gépemen fordított kód kifogástalanul a gépemen megy, nem omlik össze!
Talán mem ártana a a -O3 -at a cmake/TulipUseFile.cmake fájlban lecserélni -O2 -re.
Ezt én nem tudom leelenőrizni, csak úgy, ha nem az én processzorommal készül a kód.

**Comment by attuska** [comment]
A bátyám INTEL kétmagos processzoros aztali gépén futtatva a letöltött csomagot, azon is illegális utasítást észlel a processzor és összeomlik a tulip.
Ezen a gépenis reprodukálódik a bug.
Tehát nem AMD specifikumról van szó. Ki kell irtani a -O3 optimalizációt teljesen a fordítás során! Nem szabad csak a laptopban lévő processzornam megfelelő kódot generáltatni a C fordítóval! Az én gépeimen az újrafordítás feleslegesen produkál futtatható kódot, annak minden épeszű processzoron futnia kell!

**Comment by attuska** [comment]
https://github.com/uhulinux/ub-ubk3/issues/58

**Comment by attuska** [comment]
Két út lehetséges:
1. A gcc fejlesztőknél egy hibajelzés, hogy az O3 esetén egyes processzoroknál ne generáljon értelmezhetetlen kódot. Lehet, hogy már tudnak róla, csak mi még nem használjuk a javított változatot. A gentoo fejlesztők biztos nem tudnak ilyen hibáról, mert gentoo esetében minden a gentoo célgépre, annak processzorával folyik. Debianáal sem valószínű, mert ott minden a temérdek cál architektúrára készül. Csakis olyan disztribúciók tudhatnak erről, melyek a cál architektúrára más architektúrán készítik a binárisaikat.
2. Minden egyes csomagunknál kideríteni a hibás optimatizációt, (ez már a synaptic esetén is előfordult nálunk, mely azóta relytélyes módon megjavult) ezt a csomag forrásáanak fejlesztőinek jelezni, hogy javítsák ki, ha ezt nem teszik, akkor nekünk kell.

Az 1 -es út tűnik a leg célravezetőbbnek, de az ugyancsak nehézkes.
A 2 -es út meg nem jelenthet végső megoldást, csak az egyes csomagonál célravezető. Bármikor találhatunk újabb rakoncátlanokat.

**Comment by rezso** [comment]
Ezt biztos, hogy nem fogom megoldani. A tulip pl. teljesen felesleges cucc.
Másrészt a sed és ub_replace használatát is el kell felejteni az -O3 cseréjéhez: egyszer változzon a kód, és már nem is fog működni. De ennek sem fogok nekiállni.

**Comment by rezso** [comment]
A gcc amúgy 12.1.0-nál tart, ha nagyon akarod, frissíthetünk rá. Persze kérdés, hogy hány régi, évek óta nem karbantartott, és alapvetően felesleges csomag fog belerohadni, amikhez újabb patchek kellenének.

**Comment by attuska** [comment]
A gcc frissítése biztos nem lesz gyógyír, mert a gcc fejlesztők szerintem mit sem tudnak a fordítójuk hibájáról, mely már évek óta fennáll. Az egyes programok kidobálása, melyeknél ez előjön meg csak a vészlámpa kicsúzlizásával egyenértékű. Jobb, ha nem világít, legalább nem zavar. Én a tulip-ot nem használom, ezért szerintem is kidobásra méltó, de a fejlesztői szerint biztos nem arra való, hanem használatra. A vice is jobbára csak windózos, csak arra fejlesztik és karban tartott, noha én kedvelem, szerintem nem kidobnivaló. UBK4 -en én újraforgattam, az optimatizációját letiltottam a compile szkriptben ( a sed és ub_replace szerintem is bizonytalan) az van a tárolóban és nem az Imre által készített. Biztosan működik nálatok is jól.
Akkor kénytelenek vagyunk az estleg előbukkanó újabb illegális utasítást produkálóknál egyenként eldönteni a sorsukat, kidobni, vagy kijavítani őket (folttal), ha már a karbantaróik nem teszik ezt meg.
