### ISSUE TITLE
eduke32 SIGSEG

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#72]
Igy kezdi:
`4,0142s  ERR| Unable to set video mode: SDL_GL_CreateContext failed: Could not create GL context: GLXBadFBConfig.`

Igy végzi:
`Caught signal: SIGABRT
Szegmentálási hiba (core készült)`

Az nvidia-340 csomaggal jó.

**Comment by attuska** [comment]
Az újabb verziókhoz az UBK3 foltja használható átmeneti megoldásként.

**Comment by attuska** [comment]
Csak az Nvidia-GF 210-es kártyával csinálja, az újabb kártyával (GF-Ti) már teljesen jó a nouveauval is.

**Comment by attuska** [comment]
A frissített új UBK4 rendszeren nem indul el a nouveauval sem, az nvidia-val sem.
Az nvidia-340 csomaggal is így végzi a logja szerint:
>0       0x7fbc10aa818c /usr/lib/libc.so.6(+0x8818c) [0x7fbc10aa818c]
44,4821s FATL| Signal: SIGABRT

Szerintem, mivel nem használható, inkább ki kell dobni, hogy ne terhelje a tárolót. Ne játsszanak vele az UBK4 használói, vagy akinek kell, használjon  UBK 3-at.

**Comment by attuska** [comment]
Visszafejlesztve az UBK3 verziójára (eduke32_20211228.9887.278ba013d-1.1_amd64.ubk4.uhu)  már használható és jó, nvidia GPU-val is, nouveau és nvidia csomaggal is.

**Comment by rezso** [comment]
Ez nvidia nyűg lesz, mert intel grafikával jól megy. Persze baromi pixeles, de valószínűleg ez a duke demodata miatt van.

**Comment by attuska** [comment]
Csak teli képpel baromi pixeles a bejelentkező képe, a többi nálam laptottyon UBK4 alatt is jó.

**Comment by attuska** [comment]
Nekiáltam a javításának, mert nagyon népszerű és folyamatosan karban is van tartva.

A forrásában a Common.mak fájlban van a hiba, ahová rengeteg opimatizációt vettek be a fordító részére.
A lényeg az 542. sortól kezdve van:
>##### Optimizations
>
>fndef OPTOPT
>    ifeq ($(findstring x86_64, $(IMPLICIT_ARCH)),x86_64)
>        ifeq ($(findstring x86_64h, $(IMPLICIT_ARCH)),x86_64h)
 >           OPTOPT := -march=haswell -msse4.1 -msse4.2 -mpopcnt -mpclmul -mavx -mrdrnd -mf16c -mfsgsbase -mavx2 -maes -mfma -mbmi -mbmi2
>           # -mcrc32 -mmovbe
>      else
>         OPTOPT := -march=core2
>       endif
>      OPTOPT += -mmmx -msse -msse2 -msse3 -mssse3 -mfpmath=sse
> endif
>  ifeq ($(findstring i386, $(IMPLICIT_ARCH)),i386)
>     ifeq ($(PLATFORM),DARWIN)
>        OPTOPT := -march=nocona -mmmx -msse -msse2 -msse3
>   else
>          USE_SSE2 := 0
>          ifneq (0,$(USE_SSE2))
>              OPTOPT := -march=pentium-m
>         else
>             OPTOPT := -march=pentium3
>          endif
>          ifneq (0,$(GCC_PREREQ_4))
>              OPTOPT += -mtune=generic
>              # -mstackrealign
>          endif
>          OPTOPT += -mmmx -msse -mfpmath=sse
>          ifneq (0,$(USE_SSE2))
>              OPTOPT += -msse2
>          endif
>      endif
>  endif
> ifeq ($(PLATFORM),WII)
>       OPTOPT := -mtune=750
>    endif
>endif

Vagyis ez is szegmentációs hibát csinált eddig az **AMD Phenom(tm) II X2 545 Processor** -ral. A másik kétmagos Intellel jó.
Szerintem a -mmmx okozza ezt, ami egy rakás optimatizációt takar, valamelyiket ez az AMD nem tud. Nem az nvida-340 GPU -ja a hibás. Ezt kiirtva jó már a kód.
Az eduke-32 20211228-9887-278ba013d -as verziójában más optimatizációk vannak, ez az utolsó, amit még tud ez a processzor.
Valami jobbat kellne kitalálni, mert a teljes optimatizációt ki lehet kapcsolni, amivel szintén jó.

**Comment by attuska** [comment]
Ennek ellenére még mindig így végzi, ha abbahagyom a játékot:

Caught signal: SIGABRT
Szegmentálási hiba (core készült)
attila@derp-x8664:~$ 

Az UBK3 régebbi verziója is, a még régebbieknél jez nincs.

**Comment by rezso** [comment]
A Common.mak változásait kellene lekövetni.

**Comment by attuska** [comment]
Érdekes, hogy a bratyóm intel kétmagos gépén (Intel(R) Core(TM)2 Duo CPU     E4600  @ 2.40GHz) semmi hibát nem mutat a régi.

**Comment by attuska** [comment]
Felraktam a csomagot. https://github.com/uhulinux/ub-ubk4/commit/526b1c85233505016d5828cdc2a21ce16e4a2ad6
