### ISSUE TITLE
miniracer & mesa opengl bug

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#74]
A mesa nouveau GL esetén így végzi:
`attila@derp-x8664:~$ miniracer
Added packfile ./data/pak0.pak (133 files)
Console initialized.
PackFile: ./data/pak0.pak : textures/themes.lst
PackFile: ./data/pak0.pak : models/cars.lst
UDP Initialized
PackFile: ./data/pak0.pak : maps/maps0.lst
FindFile: ./data/maps/maps1.lst
FindFile: can't find maps/maps2.lst
Could not open maps/maps2.lst
Number of maps: 8
Loaded records
Using XFree86-VidModeExtension Version 2.2
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  154 (XFree86-VidModeExtension)
  Minor opcode of failed request:  17 (XF86VidModeGetGammaRamp)
  Value in failed request:  0x579
  Serial number of failed request:  34
  Current serial number in output stream:  34
attila@derp-x8664:~$ `
Az nvidia csomagunkkal jó.

**Comment by attuska** [comment]
A google nem segített. Ha intel videó processzorral sem megy. akkor a mesa opengl kijavíthatatlansága esetén ki kell dobni.

**Comment by attuska** [comment]
UBK3 alatt az ottani mesa-val megy.

**Comment by attuska** [comment]
UBK4 alatt semmivel nem megy (NVIDIA GeForce GTX 660 Ti).
UBK4 alatt nvida-470-el megy (NVIDIA GeForce 210).
Szerintem kidobandó UBK4 alatt, De előbb még letesztelem intel GPU-s laptopon. ( A laptottyé a jövő.)

**Comment by attuska** [comment]
Frissen telepítettem egy UBK4-et egy DELL laptottyra (Integrált Intel GPU).
A miniracer ugyanúgy nem megy, mint az nvidia-nouveau esetén a PC-n. Terminálban ugyan az az üzenete.

**Comment by attuska** [comment]
Az ub már nagyon helyesen ki lett dobva.

**Comment by rezso** [comment]
Hol lett kidobva? UBK4 alatt biztosan nem.
