### ISSUE TITLE
d2x-rebirth fordítási hiba

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#78]
`lto-wrapper: fatal error: /bin/g++ returned 1 exit status
compilation terminated.
`

**Comment by attuska** [comment]
A 2022-09-22 snapshot d2x-rebirth szekciójában van, a d1x-rebirth szekció refordul.

**Comment by rezso** [comment]
Valószínűleg újabb gcc (>= 10.3.1) kell neki.

**Comment by rezso** [comment]
Így van. A dev ágban lévő 12.2.0-s gcc-vel csont nélkül fordul.
