### ISSUE TITLE
doveconf mintha nem működne

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#79]
`attila@derp-x8664:~$ doveadm
Fatal: Error reading configuration: stat(/etc/dovecot/dovecot.conf) failed: No such file or directory
attila@derp-x8664:~$ dovecot-sysreport
doveconf: Fatal: open(/etc/dovecot/dovecot.conf) failed: No such file or directory
attila@derp-x8664:~$
`
A dovecot.conf parancs ugyancsak ezt hiányolja.

**Comment by rezso** [comment]
Egy pop3/imap szervert nyilván egyénileg kell konfigolni használat előtt. Ez nem apache, ami elketyeg egy default konfiggal is.
