### ISSUE TITLE
A calibre olvasója  Nvidia GPU-val nouveau-val megfagy.

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#80]
Nvida meghajtóval jó csak, a mesa nouveau-val belefagy, nem jelenít meg semmit.
A calibre kész binárisáról van szó.
Ha Intel GPU-val sem megy, akkor lehet, hogy az egészet ki kell dobni.

**Comment by attuska** [comment]
UBK3-on jó.

**Comment by attuska** [comment]
Intel GPU-val is jó, a laptottyomon.

**Comment by attuska** [comment]
A hiba gyökere valószínűleg közös, a mesa nouveau-ban keresendő.
Hasonló hibák, melyek nvidia hivatalossal jók:
Eduke-32: https://github.com/uhulinux/ub-ubk4/issues/72
Compiz: https://github.com/uhulinux/ub-ubk4/issues/75
Miniracer:https://github.com/uhulinux/ub-ubk4/issues/74
Google-eart: https://github.com/uhulinux/ub-ubk4/issues/8

**Comment by attuska** [comment]
A frissített új telepítményeb jó.

**Comment by attuska** [comment]
A régebbi nvidia-gf 210 GPU-jával megfagy minden funkciója.

**Comment by rezso** [comment]
Szinte biztos, hogy az nvidia cuccok körül nem gömbölyű valami. Ez már a sokadik ilyen issue.
Lehetséges, hogy olyan dolgokat használnának a progik, amiket az nvidia driverek már/még nem támogatnak. No meg a mesa is jócskán változott, a régi, „legacy” cuccok ki lettek szórva belőle. Talán már a 21.x-től, de a 22.x-nél biztos.

**Comment by attuska** [comment]
Az újabb nvidia GPU-val a meghajtóval (nvidia-470) megy rendben a hír letöltés is. A nouveauval lefagy a nem általunk készített calibre bináris. Vagyis az új mesa már nem támogatja a régebbi nvidia GPU-kat, a régi mesa viszont még igen.
A calibre meg már csak a hivatalos nvidia meghajtókkal tart lépést. Gondolom az Intel GPU-k nála kivételt képeznek, hisz ahhoz csakis a mesa nouveau létezik.
Marad a csomag,  hátha használja valaki (nekem nem kell), nem vesézem tovább.
