### ISSUE TITLE
gnome-software

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#82]
attila@derp-x8664:~$ gnome-software
09:52:21:764 libsoup libsoup3 symbols detected. Using libsoup2 and libsoup3 in the same process is not supported.
Nyomkövetési/töréspont csapda (core készült)
attila@derp-x8664:~$

**Comment by attuska** [comment]
Némileg javítva, legalább elindul, de csak a telepítetteket sorolja fel.
https://github.com/uhulinux/ub-ubk4/commit/600a04e067082400174b2f9ab9ac06b5faf3b240

**Comment by rezso** [comment]
Az érdekes az, hogy a gnome-software közvetlenül nem is függ a libsoup2-től. De ez is egy gnome katyvasz.

**Comment by attuska** [comment]
Az, de a tény, az tény. Kétlem, hogy csak nálunk van ez.

**Comment by attuska** [comment]
Lehet, hogy frissíteni kellene, mert a legújabb  verziója már 43.0, a mienk meg 42.4. Arch-nál már 43.0 van.
Ahhoz passzol a libsoup3.

**Comment by rezso** [comment]
Nálunk is 43.0 van. Csak szólok... :)

**Comment by attuska** [comment]
Akkor sem szereti a libsoup3 -at a gyakorlatban.

**Comment by rezso** [comment]
A flatpak csomagnak volt egy postinst szkriptje, amit később töröltem, mert hibára futott a postinst:
https://github.com/uhulinux/ub-ubk4/commit/f64a05101d22c625211cbe89e5b05fbab23262b8
Lehet, hogy ez hiányzik neki.

**Comment by attuska** [comment]
Megpróbáltam hozzáadni a flathub.flatpak.repo fájlt egy /etc/flatpak/remotes.d/ mappába, ezután már el sem indul, az új hibaüzenet ez:
>attila@derp-x8664:~$ gnome-software
>**
>flatpak:ERROR:common/flatpak-utils-http.c:392:flatpak_create_http_session: assertion failed (rc == CURLM_OK): (1 == 0)
Bail out! flatpak:ERROR:common/flatpak-utils-http.c:392:flatpak_create_http_session: assertion failed (rc == CURLM_OK): (1 == 0)
Félbeszakítva (core készült)
attila@derp-x8664:~$ 

Találtam egy hasonló üzenettel foglalkozó fórumot:
https://forum.kaosx.us/d/2974-discover-doesnt-start-due-to-flatpak-update

**Comment by attuska** [comment]
A discover üzenete is hasonló:
>attila@derp-x8664:/etc$ plasma-discover
qrc:/qml/Feedback.qml:2:1: module "org.kde.userfeedback" is not installed
**
flatpak:ERROR:common/flatpak-utils-http.c:392:flatpak_create_http_session: assertion failed (rc == CURLM_OK): (1 == 0)
Bail out! flatpak:ERROR:common/flatpak-utils-http.c:392:flatpak_create_http_session: assertion failed (rc == CURLM_OK): (1 == 0)
Félbeszakítva (core készült)
attila@derp-x8664:/etc$

**Comment by attuska** [comment]
Köszönöm Rezső, most már jó.
https://github.com/uhulinux/ub-ubk4/commit/1b6cabb982cbd962ce910a8fd4d40d40423b9151

**Comment by attuska** [comment]
Újabban megint nem jó, nem sorol fel semmi távolit.
attila@derp-x8664:~$ flatpak remotes

attila@derp-x8664:~$ gnome-software
10:23:34:206 Gs  Only 0 apps for recent list, hiding
10:23:34:240 Gs  failed to get featured apps: no apps to show
10:23:34:266 Gs  Only 0 apps for curated list, hiding
^C
attila@derp-x8664:~$

**Comment by attuska** [comment]
Újabb tapasztalat a MATE alatt terminálból indítva:
attila@derp-x8664:~$ gnome-software
10:31:46:404 PK  failed to set proxy: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._pk_2dengine_2derror_2dquark.Code3: setting the proxy failed: failed to get the uid
10:31:46:404 GsPluginPackageKit Failed to load proxy settings: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._pk_2dengine_2derror_2dquark.Code3: setting the proxy failed: failed to get the uid
10:31:49:325 Gs  Only 0 apps for recent list, hiding
10:31:49:362 Gs  failed to get featured apps: no apps to show
10:31:49:405 Gs  Only 0 apps for curated list, hiding
10:32:28:918 Gs  can't reliably fixup error code 13 in domain g-io-error-quark
10:32:28:919 Gs  failed to get sources: failed to process components/component/id[text()='/etc/apt/sources.list:deb http://download.ubk.hu/pkg/ubk4/main/amd64/ ./ ']/../pkgname/..|components/component[@type='web-application']/id[text()='/etc/apt/sources.list:deb http://download.ubk.hu/pkg/ubk4/main/amd64/ ./ ']/..|component/id[text()='/etc/apt/sources.list:deb http://download.ubk.hu/pkg/ubk4/main/amd64/ ./ ']/..: predicate [text()=' was unfinished, missing ']'
10:33:11:728 Gs  can't reliably fixup error code 13 in domain g-io-error-quark
10:33:11:729 Gs  failed to get sources: failed to process components/component/id[text()='/etc/apt/sources.list:deb http://download.ubk.hu/pkg/ubk4/main/amd64/ ./ ']/../pkgname/..|components/component[@type='web-application']/id[text()='/etc/apt/sources.list:deb http://download.ubk.hu/pkg/ubk4/main/amd64/ ./ ']/..|component/id[text()='/etc/apt/sources.list:deb http://download.ubk.hu/pkg/ubk4/main/amd64/ ./ ']/..: predicate [text()=' was unfinished, missing ']'
^C
attila@derp-x8664:~$ 
![gnome-sofware](https://user-images.githubusercontent.com/6311614/198826813-487c8cef-4863-4db8-89f2-73bf14f9d978.jpg)

**Comment by attuska** [comment]
"Megjavítottam"
Mégiscak kell a flatpaknak a postinst szkript.
root@derp-x8664:/home/attila# glib-compile-schemas /usr/share/glib-2.0/schemas/
root@derp-x8664:/home/attila# flatpak remote-add --if-not-exists flathub /usr/share/flatpak/flathub.flatpakrepo

Note that the directory 

'/root/.local/share/flatpak/exports/share'

is not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

root@derp-x8664:/home/attila# 

**Jó lenne ezt csomagszintre emelni...**

**Comment by rezso** [comment]
https://github.com/uhulinux/ub-ubk4/commit/4132f594791b485ac0f74c4494c441d07e35f29c
