### ISSUE TITLE
cinnamon

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#83]
A cinnamon csak tartalék módban indul nálam.

**Comment by attuska** [comment]
A python downgrade nem tette helyre.

**Comment by attuska** [comment]
Eddig egyetlen frissítés sem hozta helyre nálam. Belépéskor továbbra is  erre a tartalék módra figyelmeztető ablak van, az abban levő lehetőségek alkalmazása hatástalan. Csak a MATE panel van felül, a kilépéskor felbukkanó megerősítési jóváhagyási ablak cinnamon stílusú, és a háttér baglyos, nem MATE stílusú. Még jó, hogy a a MATE panelen lévő cuccok működnek, de így értelmetlen az egész cinnamon használata. Én nem tudom kideríteni a hiba okát, nem is fogom.
Felőlem ezt a rendszert is ki kellene hajítani mindenestül az UBK4-ből. UBK3 alatt a kedvenceim közé tartozott, akinek hiányzik használjon UBK3 rendszert a régebbi cinnamonnal, vagy egy Linux-MINT -et, vagy egy rolling disztrót.

**Comment by rezso** [comment]
Én nagyon sok mindent kidobnék, de nagy valószínűséggel jó részük visszakerülne...

**Comment by rezso** [comment]
[xorg-session.log](https://github.com/uhulinux/ub-ubk4/files/10025228/xorg-session.log)

**Comment by rezso** [comment]
Én sem fogom javítgatni. Python alapú okádék, folyamatosan lemaradva mindenben.

**Comment by rezso** [comment]
https://github.com/uhulinux/ub-ubk4/commit/8ddeb3a14cbbc8a56c6ee8a15aa00124accb21e8
