### ISSUE TITLE
lxde

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#84]
Az lxde menüje használhatatlanul kicsi-

**Comment by rezso** [comment]
Van még értelme az lxde-nek?

**Comment by attuska** [comment]
Gentoo-nál , Arch-linuxnál, Fedoránál még van.

**Comment by attuska** [comment]
Megjavult valami érthetetlen módon. Előtte visszafejlesztettem a python-t, azzal jó lett, majd az új pythonnal is már jó.
