### ISSUE TITLE
Mate terminál

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#86]
Mate terminál

**Comment by attuska** [comment]
A mate terminál alapértelmezettem  a rndszertémát használja.
A színek ebben az esetben:
Háttér: fekete
Szövegszín: fekete
Vagyis nem látszik semmi benne.
Ha átállítom a teminál beállításait másra, ami kezdetben nincs, akkor ideoglenesen erre váltok, akkor már látható.
Ha a rendszertéma használata mezőben lévő pipát kiveszem, akkoz ez már állandósul.

**Comment by attuska** [comment]
A rendzsrtéma használa mezőben a pipa törlendő, akkor jó lesz.

**Comment by rezso** [comment]
Szerintem ez rendszertémától is függ.
