### ISSUE TITLE
nvidia csomagok

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#87]
A gnome nem indul el wayland felületen egyik nvidia csomagunkkal sem.
A nouveau-val elindul waylandon is.

**Comment by attuska** [comment]
A compizzal a komplikáltabb ablakok ( firefox, synaptic, satöbbi) lötyögtetése nvidia csomagokkal akadozó, a nouveauval sima.
Ez is OpenGL hiba lehet valószínüleg.

**Comment by attuska** [comment]
UBK3 alatt minden rendben lévőnek tűnik.

**Comment by attuska** [comment]
A gentoo a wayland használatát a 470-estől felfele engedélyezheti egy use flaggal. Alatta nem!
Szerintem nálunk is megcsinálható, hogy működjön, de csak a 470-es kipróbálására van lehetőségem.

**Comment by rezso** [comment]
Ahogy látom, elég sok a gond az nvidia csomagokkal, sok az inkompatibilitás. Szerintem csak az újabb nvidia drivereket kellene megtartani (470, és a jelenleg 525), és ami azzal nem megy, az kuka. A régi driverek a régi kártyákhoz valók, ami régi gépekben vannak. Azokon meg a mostani rendszerek csak döcögősen mennek.

**Comment by attuska** [comment]
Az én lehetőségem a 470-es kipróbálása az egyik gépen, ami lefele kompatibilis mindennel. A 390-es és 340 is jó hozzá. Azon a gnome, és plasma waylandon is elindult régen a 390-essel és 470-essel. Most nem megy egyikkel sem, ennek meg kellene találni az okát és orvosolni.  A plasma csak X-en megy a nouveauval, ő is ment végre fagyás nélkül a hivatalosakkal.

A másikhoz meg csak meg a 420-as sorozat a jó, azon a gnome waylandon a nouveauval ment és megy.

A sway nouveauval mindegyiken megy, nvidia-val és X-en nyilván nem.

A kukázással nem értek egyet, mert sokan használnak és használni is fognak nvidia GPU-t a gépeikben, remélem nem csak windóz alatt.

Vannak duál GPU-s masinák is, Rigó Imi megoldotta a régi UBK4 -en, hogy használja a masinája az nvidia GPU-t, most már nem tudja, csak az Intel-t.

Figyelni kell rolling disztrókat, ők nem a régi gépekre specializálódtak. Amelyik dobja a sorozatot, az mehet valóban a kukába.

**Comment by rezso** [comment]
Ami kritikus lehet: nvidia, mesa, libglvnd. Mindegyiken csak annyit módosítok, amennyit muszáj (pl. megszűnt build opció). Persze kerneltől is függ. Szóval ezzel nem sokat tudok kezdeni. Ami biztos: a calamares-ben is emelve lesznek a követelmények, 8 GB lemez és 4 GB ram igény lesz a minimum.

**Comment by attuska** [comment]
Rigó Imi most már beüzemelte a laptottyán az nvidia-t is, de az UBK4-et csak Intel laptopon lehet (talán) használni.
Ezért szerintem ki kell dobni az összes nvidia cuccot, az nvidia GPU-val rendelkezők meg használjanak más disztrót!
Vagy windózt.
