### ISSUE TITLE
sddm-config-editor

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#88]
Az sddm-contig editor már nem menti, vagy nem jó helyre a beállításokat.
Az sddm téma váltása csakis úgy mehet, ha a /usr/lib/sddm/sddm.conf.d/default.conf fájlt átszerkesztem. A breeze téma jó!

**Comment by rezso** [comment]
Az is egy régi progi. Találtam egy forkot, az elvileg kezeli az /etc/sddm.conf.d/ alatti konfigokat.

**Comment by attuska** [comment]
A MATE alatt nem lelem a desktop indítóját. LXQT, JWM, Icewm alatt megvan, szép angolul: SDDM settings. Azokban ikonja is van. Gyanús nekem ez, hogy csak mate alatt van. (https://github.com/uhulinux/ub-ubk4/issues/73)
Az fvwm xdg menüje is ezt bizonyítja, mert abban van mate, lxqt menü szekció is.

**Comment by rezso** [comment]
MATE alatt is megvan, félig-meddig logikus helyen: Renszer menü / Beállítások / Megjelenés.
Mivel a desktop fájlban a Categories=Settings;Qt, a Beállítások még érthető, de miért épp a Megjelenés?

**Comment by attuska** [comment]
Na, ott a megjelenés alatt nem kerestem. Ki gondolta volna???

**Comment by rezso** [comment]
Én sem gondoltam volna. Csakhogy a mate menürendszer úgy van kitalálva, hogyha benne van a Qt a Categories sorban, akkor a "Look & Feel", azaz Megjelenés részbe kerül. Ki fogom szedni belőle ezt, nem minden Look & Feel, ami Qt.

**Comment by attuska** [comment]
A téma előnézetéből nem tudok visszalépni, ezt a preview ablakot becsukva kilép az egész, újra kell indítani az sddm-config-editort az újabb téma kiválasztásához és megtekintéséhez, majd újra megismétlődik az előbb leírt. Ez bizony hiba, amit a fejlesztő talán orvosolhatna, ha tudna róla.

**Comment by rezso** [comment]
A képernyő bal felső sarkában megjelenik egy 'Close %1 preview' mini ablak, azzal ki lehet lépni az előnézetből.
Ha van felső panel, kitakarja benne az Alkalmazások menü részt. Nem egyszerű észrevenni, de van.
![Képernyőkép 2022-11-24 15-51-22](https://user-images.githubusercontent.com/2437550/203813242-55dd40c9-7f1c-4614-a3ff-2a6e54f5cfb1.png)

**Comment by attuska** [comment]
Igen, de akkor az sddm-config-editor is abbahagyja!
