### ISSUE TITLE
exfat kezelés grafikusan

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#93]
A gparted progink fent említett Microsoft fejlesztésű fájlrendszert csak halványan írja ki, kezelni nem tudja.
Ezt használják és értelmezik manapság a nagyobb méretű háttértárolók, laptopok, tévék satöbbi.
A gparted keresné az az exfat.h-t a fordításkor, de az nincs. Az exfat-utils forrásában van, de ez nem telepszik automatikusan, lehet, hogy jó lenne neki.
Az átlagos júzer soha nem fog parancssort használni!

**Comment by attuska** [comment]
Ez volt egy mostanában vett 128 Gigás pendrájvomon. Nem véletlen rakták rá, és nem a fat32 -t, ami mára már felejtős.
Nem jó a gpartednek a módosított exfat-utils, habár a próbámnál most a módosított exfat-utils csomagból már megleli az exfat.h-t.
A gparted readme fájljában az  exfat kezeléshez szükséges csomag neve exfatprogs, ami nálunk nics, ez keményen ütközne az exfat-utils csomagunkkal. Az Arch-linuxnál megvan az exfatprogs csomag, és ennek megléte kellene a gparted csomag fordításához és ennek telepítve is kellene lennie, ekkor talán a gparted már tudná kezelni a Microsoft specifikus exfat fájlendszert is.

Jó lenne, ha az alapértelmezetten a MATE isónkra jó gparted kerülne végre.

**Comment by rezso** [comment]
Végre? Eddig sem volt, most kezdett el zavarni?
Amúgy a gparted is és a kpmcore is binárisokat futtat (pl. fsck.exfat), nem kell neki semmilyen extra forrás. Felesleges is lenne.
Csináltam egy módosított exfat-utils csomagot, ami valójában az exfatprogs forrásából készül, de csomagnévnek jobb az exfat-utils. Amúgy a gparted okosan felismeri, hogy a bináris az exfat-utils vagy az exfatprogs csomagból van-e.
Csináltam egy mkexfatfs szimlinket is, hogy a kpmcore azt is megtalálja.
Függőségként egyik csomagnak sem állítom be, a többi (btrfs-progs, xfsprogs, reiser4progs, reiserfsprogs, jfsprogs, fuse, e2fsprogs) sem függősége egyiknek sem.

**Comment by rezso** [comment]
Itt látszik, hogy a gparted is, és a kpmcore is exfat-utils / exfatprogs binárisokat használ:

https://github.com/KDE/kpmcore/blob/b3fb2064b7a9160d69032d1ef4c8be8e7f09a71c/src/util/externalcommand_whitelist.h
https://github.com/GNOME/gparted/commit/4a8495205814e72c1b900da1cedae4e8175c8173

Még annyit, hogy az exfat-utils 1.3.0 2018 szeptemberi, az 1.4.0 2023 március 2-i. Azaz két release között eltelt vagy 4 és fél év.

**Comment by miklosakos** [comment]
`exfat-utils` telepites utan tudtam formazni egy pendriveot exfatra es sikeresen felcsatolni grafikus feluletrol.
<img width="790" alt="image" src="https://user-images.githubusercontent.com/8452012/229384054-b3ce7359-2b61-473b-9134-4a7b66d364e7.png">
